import { ActionHandler } from '../src/action-handler';
import type { FeedbackEntry } from '../src/types';
import type { ClassificationResult } from '../src/classifier';
import type { PrioritizedItem } from '../src/prioritizer';

function makeItem(priority: 'critical' | 'high' | 'medium' | 'low' = 'medium'): PrioritizedItem {
  const feedback: FeedbackEntry = {
    id: 'fb-1', type: 'issue', source: 'user', targetType: 'code', targetId: 'src/main.ts',
    content: 'Missing input validation on login form', severity: 'error', decision: 'pending',
    createdAt: new Date().toISOString(), tags: ['auth'],
  };
  const classification: ClassificationResult = { category: 'bug', confidence: 0.9, matchedKeywords: ['validation'] };
  return { feedback, classification, impact: 3, effort: 2, priority };
}

describe('ActionHandler', () => {
  it('should create an issue with default implementation', async () => {
    const handler = new ActionHandler();
    const item = makeItem('high');
    const result = await handler.createIssue(item);
    expect(result.success).toBe(true);
    expect(result.actionType).toBe('create_issue');
    expect(result.details!.title).toContain('[HIGH]');
    expect(result.details!.feedbackId).toBe('fb-1');
  });

  it('should generate a task with default implementation', async () => {
    const handler = new ActionHandler();
    const item = makeItem('critical');
    const result = await handler.generateTask(item);
    expect(result.success).toBe(true);
    expect(result.actionType).toBe('generate_task');
    expect(result.details!.targetId).toBe('src/main.ts');
  });

  it('should respond with default implementation', async () => {
    const handler = new ActionHandler();
    const item = makeItem('low');
    const result = await handler.respond(item);
    expect(result.success).toBe(true);
    expect(result.actionType).toBe('respond');
    expect(result.details!.autoGenerated).toBe(true);
  });

  it('should use custom createIssue when provided', async () => {
    const handler = new ActionHandler({
      createIssue: async () => ({ success: true, actionType: 'create_issue', message: 'custom issue' }),
    });
    const result = await handler.createIssue(makeItem());
    expect(result.message).toBe('custom issue');
  });

  it('should auto-handle when options are enabled', async () => {
    const handler = new ActionHandler({
      autoCreateIssues: true,
      autoRespond: true,
      createIssue: async () => ({ success: true, actionType: 'create_issue', message: 'auto issue created' }),
      respond: async () => ({ success: true, actionType: 'respond', message: 'auto response sent' }),
    });
    const results = await handler.handle(makeItem('critical'));
    expect(results).toHaveLength(2);
    expect(results[0].actionType).toBe('create_issue');
    expect(results[1].actionType).toBe('respond');
  });

  it('should return empty array when no auto options are enabled', async () => {
    const handler = new ActionHandler();
    const results = await handler.handle(makeItem());
    expect(results).toHaveLength(0);
  });
});
