import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const covPath = path.join(root, 'coverage', 'coverage-summary.json');

let cov = { statements: 0, branches: 0, functions: 0, lines: 0 };
let tests = { suites: 0, tests: 0 };

try {
  if (fs.existsSync(covPath)) {
    const raw = JSON.parse(fs.readFileSync(covPath, 'utf8'));
    const total = raw.total;
    cov = {
      statements: total.statements.pct,
      branches: total.branches.pct,
      functions: total.functions.pct,
      lines: total.lines.pct,
    };
  }
} catch { /* cov json not found */ }

const historyPath = path.join(root, '.ai-devkit', 'coverage-history.json');
let history: { date: string; statements: number; branches: number; tests: number }[] = [];
try {
  const raw = JSON.parse(fs.readFileSync(historyPath, 'utf8'));
  if (Array.isArray(raw)) {
    history = raw.filter((e: unknown): e is { date: string; statements: number; branches: number; tests: number } =>
      typeof e === 'object' && e !== null && 'date' in e && 'statements' in e
    );
  }
} catch { /* new history */ }

fs.writeFileSync(historyPath, JSON.stringify(history, null, 2));

const target = 90;
const lastEntry = history.length >= 2 ? history[history.length - 2] : null;
const stmtsDelta = lastEntry ? cov.statements - lastEntry.statements : 0;

// QW7: Coverage delta alert
if (lastEntry) {
  if (stmtsDelta < -3) {
    console.error(`[cov-tracker] CRITICAL: Coverage dropped by ${Math.abs(stmtsDelta).toFixed(2)}pp (exceeds -3pp threshold)`);
    process.exitCode = 1;
  } else if (stmtsDelta < -1) {
    console.warn(`[cov-tracker] WARNING: Coverage dropped by ${Math.abs(stmtsDelta).toFixed(2)}pp`);
    // Create pendencia for this drop
    const pendenciasPath = path.join(root, '.ai', 'audit', 'pendencias.jsonl');
    if (fs.existsSync(path.dirname(pendenciasPath))) {
      const pendencia = {
        id: `cov-${Date.now()}`,
        severity: stmtsDelta < -3 ? 'critical' : 'high',
        category: 'coverage',
        checkName: 'coverage-tracker',
        message: `Coverage dropped by ${Math.abs(stmtsDelta).toFixed(2)}pp (${lastEntry.statements.toFixed(2)}% → ${cov.statements.toFixed(2)}%)`,
        createdAt: new Date().toISOString(),
        status: 'open',
        source: 'continuous' as const,
      };
      try {
        fs.appendFileSync(pendenciasPath, JSON.stringify(pendencia) + '\n');
      } catch {}
    }
  }
}

const bar = (val: number, max: number, w: number = 20): string => {
  const filled = Math.round((val / max) * w);
  return '█'.repeat(Math.min(filled, w)) + '░'.repeat(Math.max(0, w - filled));
};

const phaseStatus = (threshold: number): string => {
  if (cov.statements >= threshold) return '✅ Complete';
  if (cov.statements >= threshold - 5) return '🔄 Near Complete';
  return '⬜ Not Yet';
};

const dashboard = `# Coverage Progress Dashboard

**Last updated:** ${new Date().toISOString().slice(0, 19)}

## Summary

| Metric | Current | Target | Gap | Progress |
|--------|---------|--------|-----|----------|
| **Statements** | ${cov.statements.toFixed(2)}% | ${target}% | ${(target - cov.statements).toFixed(2)}pp | ${bar(cov.statements, target)} |
| **Branches** | ${cov.branches.toFixed(2)}% | ${target}% | ${(target - cov.branches).toFixed(2)}pp | ${bar(cov.branches, target)} |
| **Functions** | ${cov.functions.toFixed(2)}% | ${target}% | ${(target - cov.functions).toFixed(2)}pp | ${bar(cov.functions, target)} |
| **Lines** | ${cov.lines.toFixed(2)}% | ${target}% | ${(target - cov.lines).toFixed(2)}pp | ${bar(cov.lines, target)} |

## Test Progress

| Metric | Value |
|--------|-------|
| **Test Suites** | ${tests.suites || 'Run npm run test:cov first'} |
| **Tests** | ${tests.tests || 'Run npm run test:cov first'} |
| **Delta (last run)** | ${stmtsDelta >= 0 ? '+' : ''}${stmtsDelta.toFixed(2)}pp |

## Historical Record

| Date | Statements | Branches | Tests |
|------|-----------|----------|-------|
${history.slice(-10).map((e: { date: string; statements: number; branches: number; tests: number }) => `| ${e.date.slice(0, 10)} | ${e.statements.toFixed(2)}% | ${e.branches.toFixed(2)}% | ${e.tests} |`).join('\n')}

## Phase Status

| Phase | Target | Current | Status |
|-------|--------|---------|--------|
| 1 - Quick Wins | 40% | ${cov.statements.toFixed(2)}% | ${phaseStatus(40)} |
| 2 - Core Runtime | 55% | ${cov.statements.toFixed(2)}% | ${phaseStatus(55)} |
| 3 - Local AI & Security | 67% | ${cov.statements.toFixed(2)}% | ${phaseStatus(67)} |
| 4 - Commands | 82% | ${cov.statements.toFixed(2)}% | ${phaseStatus(82)} |
| 5 - Hardening | 90%+ | ${cov.statements.toFixed(2)}% | ${phaseStatus(90)} |

## Usage

<!-- usage -->
*Dashboard auto-generated by scripts/audit/coverage-tracker.ts*
`;

const outDir = path.join(root, '.ai-devkit');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'coverage-dashboard.md'), dashboard);
console.log(`[cov-tracker] Statements: ${cov.statements.toFixed(2)}% | History: ${history.length} entries`);
console.log(`[cov-tracker] Dashboard: ${path.join(outDir, 'coverage-dashboard.md')}`);