import * as fsp from 'fs/promises'
import { createLogger } from '@ideia/logger'
import { SkillsDistillationInput, SkillsDistillationOutput } from './types'

const logger = createLogger('g0-g9-cycle:skills-distiller')

export class SkillsDistiller {
  async distill(input: SkillsDistillationInput): Promise<SkillsDistillationOutput> {
    const distilledSkills: string[] = []
    const steeringUpdated: string[] = []

    if (input.lessons.length === 0) {
      logger.warn('No lessons to distill for cycle', { cycleId: input.cycleId })
      return {
        passed: false,
        distilledSkills: [],
        steeringUpdated: [],
        lessonsCount: 0,
      }
    }

    for (const lesson of input.lessons) {
      const skillName = this.lessonToSkillName(lesson, input.featureName)
      const skillContent = this.buildSkillContent(lesson, input.cycleId)
      distilledSkills.push(skillName)

      const skillPath = `.skills/${skillName}.md`
      await this.ensureDir(skillPath)
      await fsp.writeFile(skillPath, skillContent, 'utf-8')
      logger.info('Skill distilled', { skill: skillName, path: skillPath })
    }

    for (const steeringPath of input.steeringPaths) {
      try {
        const existing = await fsp.readFile(steeringPath, 'utf-8')
        const update = this.appendLessonToSteering(existing, input, steeringPath)
        await fsp.writeFile(steeringPath, update, 'utf-8')
        steeringUpdated.push(steeringPath)
      } catch {
        await this.ensureDir(steeringPath)
        const steering = this.buildSteeringFile(input)
        await fsp.writeFile(steeringPath, steering, 'utf-8')
        steeringUpdated.push(steeringPath)
      }
    }

    return {
      passed: distilledSkills.length > 0,
      distilledSkills,
      steeringUpdated,
      lessonsCount: input.lessons.length,
    }
  }

  private lessonToSkillName(lesson: string, featureName: string): string {
    const slug = lesson
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 40)
    return `${featureName.toLowerCase().replace(/\s+/g, '-')}-${slug}`
  }

  private buildSkillContent(lesson: string, cycleId: string): string {
    return [
      `# Skill: ${lesson}`,
      '',
      `**Origin:** G9 distillation from cycle ${cycleId}`,
      `**Date:** ${new Date().toISOString()}`,
      '',
      '## Lesson',
      '',
      lesson,
      '',
      '## Application',
      '',
      '- Reuse in similar feature contexts',
      '- Reference during G3 (Spec) and G4 (Review) phases',
      '',
    ].join('\n')
  }

  private async ensureDir(filePath: string): Promise<void> {
    const dir = filePath.substring(0, filePath.lastIndexOf('/'))
    await fsp.mkdir(dir, { recursive: true })
  }

  private appendLessonToSteering(existing: string, input: SkillsDistillationInput, _path: string): string {
    const entries = input.lessons.map(l => `- [${input.cycleId}] ${l}`).join('\n')
    return existing + `\n\n## Lessons from ${input.featureName} (${input.cycleId})\n\n${entries}\n`
  }

  private buildSteeringFile(input: SkillsDistillationInput): string {
    return [
      `# Steering File — ${input.featureName}`,
      '',
      `**Cycle:** ${input.cycleId}`,
      `**Generated:** ${new Date().toISOString()}`,
      '',
      '## Lessons',
      '',
      ...input.lessons.map(l => `- ${l}`),
      '',
      '## Session Logs',
      '',
      ...input.sessionLogs.map(l => `- ${l.slice(0, 100)}...`),
      '',
      '---',
      '',
      '*Auto-generated by IDEIA G9 Skills Distiller*',
    ].join('\n')
  }
}
