import { createLogger } from '@ideia/logger'
import { BlueprintADR, ScaffoldContext } from './types'

const logger = createLogger('adr-generator')

export class ADRGenerator {
  generate(adr: BlueprintADR, context: ScaffoldContext): string {
    const now = new Date().toISOString().split('T')[0]
    return [
      `# ADR: ${adr.title}`,
      '',
      `**Project:** ${context.projectName}`,
      `**Date:** ${now}`,
      `**Status:** ${adr.status}`,
      '',
      '## Context',
      '',
      adr.context,
      '',
      '## Decision',
      '',
      adr.decision,
      '',
      '## Consequences',
      '',
      ...adr.consequences.map(c => `- ${c}`),
      '',
      '---',
      '',
      `*Generated by @ideia/blueprint-scaffold*`,
    ].join('\n')
  }

  generateDefaultADRs(context: ScaffoldContext): Array<{ filename: string; content: string }> {
    const adrs: Array<{ filename: string; content: string }> = [
      {
        filename: 'adr/001-project-architecture.md',
        content: this.generate({
          title: 'Project Architecture',
          context: `The project ${context.projectName} requires a defined architecture pattern. Clean Architecture with DDD was chosen for maintainability and testability.`,
          decision: 'Adopt Clean Architecture with Domain-Driven Design principles. Structure code into modules: contract, application, infrastructure, and presentation layers.',
          consequences: ['Clear separation of concerns', 'Testable business logic', 'Higher initial setup cost', 'Requires developer discipline'],
          status: 'Accepted',
        }, context),
      },
    ]
    logger.info(`Default ADRs generated`, { count: adrs.length })
    return adrs
  }
}
