// ==========================================================================
// report-generator.ts
// ==========================================================================

import type { BiasReport } from "./types";

export class BiasReportGenerator {
  toMarkdown(report: BiasReport): string {
    const severityMap: Record<string, string> = { none: "none", low: "low", medium: "medium", high: "high", critical: "!!" };
    const lines: string[] = [
      "# Bias Detection Report",
      "> **" + report.overallStatus.toUpperCase() + "** | Score: " + (report.compositeScore * 100).toFixed(1) + "%",
      "",
      "## Metadata",
      "",
      "| Field | Value |",
      "|-------|-------|",
      "| Model | " + report.metadata.modelName + " |",
      "| Domain | " + report.metadata.domain + " |",
      "| Sample | " + report.metadata.sampleSize + " |",
      "| Priv | " + report.metadata.privilegedCount + " |",
      "| Unpriv | " + report.metadata.unprivilegedCount + " |",
      "",
      "## Metrics",
      "",
      "| Metric | Value | Threshold | Status | Severity |",
      "|--------|-------|-----------|--------|----------|",
    ];
    for (const m of report.metrics) {
      lines.push("| " + m.displayName + " | " + (m.value * 100).toFixed(1) + "% | " + (m.threshold * 100).toFixed(0) + "% | " + (m.passed ? "PASS" : "FAIL") + " | " + (severityMap[m.severity] ?? "") + " " + m.severity + " |");
    }
    lines.push("");
    if (report.criticalViolations.length > 0) {
      lines.push("## Critical Violations", "");
      for (const v of report.criticalViolations) lines.push("- **!!** " + v);
      lines.push("");
    }
    if (report.recommendations.length > 0) {
      lines.push("## Recommendations", "");
      for (const r of report.recommendations) lines.push("1. " + r);
      lines.push("");
    }
    lines.push(
      "## Audit",
      "",
      "- Report Hash: `" + report.reportHash + "`",
      "- Prev Hash: `" + (report.previousHash ?? "(genesis)") + "`",
      "",
      "---",
      "*Generated by IDEIA Bias Detection v" + report.detectorVersion + "*"
    );
    return lines.join("\n");
  }

  toHtml(report: BiasReport): string {
    const statusColor: Record<string, string> = { pass: "#3fb950", warn: "#d29922", fail: "#f85149" };
    const rows = report.metrics.map(m =>
      "<tr><td>" + m.displayName + "</td><td>" + (m.value * 100).toFixed(1) + "%</td><td>" + (m.threshold * 100).toFixed(0) + "%</td><td style=\"color:" + (m.passed ? "#3fb950" : "#f85149") + "\">" + (m.passed ? "PASS" : "FAIL") + "</td><td>" + m.severity + "</td></tr>"
    ).join("\n");
    const style = "body{font-family:sans-serif;max-width:1000px;margin:0 auto;padding:2rem;background:#0d1117;color:#c9d1d9}h1{color:#58a6ff}table{border-collapse:collapse;width:100%}th,td{border:1px solid #30363d;padding:0.5rem;text-align:left}th{background:#161b22}";
    return "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Bias Report</title><style>" + style + "</style></head><body><h1>Bias Detection Report</h1><div style=\"padding:1rem;border-radius:6px;margin:1rem 0;background:" + statusColor[report.overallStatus] + "22;border:2px solid " + statusColor[report.overallStatus] + ";color:" + statusColor[report.overallStatus] + ";text-align:center;font-weight:bold\">" + report.overallStatus.toUpperCase() + " &mdash; Score: " + (report.compositeScore * 100).toFixed(1) + "%</div><h2>Metrics</h2><table><tr><th>Metric</th><th>Value</th><th>Threshold</th><th>Status</th><th>Severity</th></tr>" + rows + "</table></body></html>";
  }

  toJson(report: BiasReport): string { return JSON.stringify(report, null, 2); }
}
