import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { LLMProvider, ChatRequest, ChatResponse, EmbeddingRequest, EmbeddingResponse, ProviderRouter } from '@ideia/llm-provider';
import {
  LangGraphAgent,
  LangGraphStateAnnotation,
  createLangGraphAgent,
  createAnalystNode,
  createArchitectNode,
  createProgrammerNode,
  createReviewerNode,
  createTesterNode,
  createDevOpsNode,
  createSupervisorNode,
  createDefaultEdgeConditions,
  createReviewerTesterParallelNode,
} from '../src';

function createMockProvider(name: string, responseContent: string): LLMProvider {
  return {
    name,
    chat: jest.fn(async (_request: ChatRequest, _signal?: AbortSignal): Promise<ChatResponse> => ({
      content: responseContent,
      model: 'mock-model',
      provider: name,
      usage: { promptTokens: 10, completionTokens: 20, totalTokens: 30 },
    })),
    embed: jest.fn(async (_request: EmbeddingRequest): Promise<EmbeddingResponse> => ({
      embeddings: [[0.1, 0.2, 0.3]],
      model: 'mock-model',
      provider: name,
    })),
  };
}

describe('Multi-Turn Integration — LangGraph with LLM Provider', () => {
  let agent: LangGraphAgent;
  let mockProvider: LLMProvider;

  beforeEach(() => {
    mockProvider = createMockProvider('ollama', 'Generated by mock LLM');
    agent = createLangGraphAgent({
      maxIterations: 10,
      nodeTimeout: 5000,
      maxRetries: 1,
    });
  });

  describe('Provider Integration in Nodes', () => {
    it('should use provider when available in analyst node', async () => {
      const node = createAnalystNode(mockProvider);
      const state: LangGraphStateAnnotation = {
        input: 'Build a REST API',
        context: {},
        currentRole: 'analyst',
        outputs: {},
        decisions: [],
        artifacts: [],
        errors: [],
        completed: false,
        messages: [],
      };

      const result = await node(state);

      expect(mockProvider.chat).toHaveBeenCalledTimes(1);
      const callArg = (mockProvider.chat as ReturnType<typeof jest.fn>).mock.calls[0][0] as { messages: Array<{ role: string; content: string }> };
      expect(callArg.messages.length).toBeGreaterThanOrEqual(2);
      expect(callArg.messages[0].role).toBe('system');
      expect(callArg.messages[1].role).toBe('user');
      expect(callArg.messages[1].content).toContain('Build a REST API');
      expect(result.outputs?.analyst).toContain('Generated by mock LLM');
    });

    it('should fall back to stub when no provider in analyst node', async () => {
      const node = createAnalystNode();
      const state: LangGraphStateAnnotation = {
        input: 'Build a REST API',
        context: {},
        currentRole: 'analyst',
        outputs: {},
        decisions: [],
        artifacts: [],
        errors: [],
        completed: false,
        messages: [],
      };

      const result = await node(state);

      expect(result.outputs?.analyst).toContain('Analisando requisitos');
    });
  });

  describe('ProviderRouter Fallback', () => {
    it('should use primary provider when available', async () => {
      const primary = createMockProvider('primary', 'Primary response');
      const fallback = createMockProvider('fallback', 'Fallback response');

      agent.registerProvider(primary);
      agent.registerProvider(fallback);
      agent.setProviderPriority(['primary', 'fallback']);

      const active = agent.getActiveProvider();
      expect(active).toBeDefined();
      expect(active!.name).toBe('primary');
    });

    it('should fall back to secondary when primary fails', async () => {
      const primary = createMockProvider('primary', 'Primary response');
      const fallback = createMockProvider('fallback', 'Fallback response');

      agent.registerProvider(primary);
      agent.registerProvider(fallback);
      agent.setProviderPriority(['primary', 'fallback']);

      agent.addNode('analyst', createAnalystNode(agent.getActiveProvider()));
      const state: LangGraphStateAnnotation = {
        input: 'Test input',
        context: {},
        currentRole: 'analyst',
        outputs: {},
        decisions: [],
        artifacts: [],
        errors: [],
        completed: false,
        messages: [],
      };

      const analystNode = createAnalystNode(agent.getActiveProvider());
      const result = await analystNode(state);

      expect(result.outputs?.analyst).toContain('Primary response');
    });

    it('should return undefined when no providers registered', () => {
      const emptyAgent = createLangGraphAgent();
      expect(emptyAgent.getActiveProvider()).toBeUndefined();
    });
  });

  describe('Multi-Turn Workflow', () => {
    it('should execute full multi-agent workflow with mock provider', async () => {
      const provider = createMockProvider('ollama', 'Step completed by LLM');

      agent.addNode('analyst', createAnalystNode(provider));
      agent.addNode('architect', createArchitectNode(provider));
      agent.addNode('programmer', createProgrammerNode(provider));
      agent.addNode('reviewer', createReviewerNode(provider));
      agent.addNode('tester', createTesterNode(provider));
      agent.addNode('devops', createDevOpsNode(provider));
      agent.addNode('supervisor', createSupervisorNode());
      agent.addNode('parallel_reviewer_tester', createReviewerTesterParallelNode(provider));

      const edges = createDefaultEdgeConditions();
      for (const [from, condition] of Object.entries(edges)) {
        agent.addConditionalEdge(from, condition);
      }

      agent.setEntryPoint('analyst');

      const result = await agent.invoke('Create a user authentication module');

      expect(result.finalState).toBeDefined();
      expect(result.summary).toBeDefined();
      expect(result.finalState.completed).toBe(true);
      expect(result.summary.completedNodes).toBeGreaterThan(0);
      expect(result.finalState.outputs.analyst).toContain('Step completed by LLM');
      expect(result.finalState.outputs.architect).toContain('Step completed by LLM');
      expect(result.finalState.outputs.programmer).toBeDefined();
      expect(result.finalState.errors).toHaveLength(0);
    });

    it('should pass context between nodes in sequence', async () => {
      const analystProvider = createMockProvider('ollama', 'Analysis: needs JWT auth, user CRUD, password hashing');
      const architectProvider = createMockProvider('ollama', 'Architecture: Express + PostgreSQL + JWT');

      agent.addNode('analyst', createAnalystNode(analystProvider));
      agent.addNode('architect', createArchitectNode(architectProvider));

      agent.addEdge('analyst', 'architect');
      agent.addEdge('architect', 'end');

      agent.setEntryPoint('analyst');

      const result = await agent.invoke('Build auth system');

      expect(result.finalState.outputs.analyst).toContain('Analysis');
      expect(result.finalState.outputs.architect).toContain('Architecture');
      expect(result.finalState.outputs.architect).toBe(result.finalState.outputs.architect);
    });

    it('should handle errors gracefully during LLM failures', async () => {
      const failingProvider: LLMProvider = {
        name: 'failing',
        chat: jest.fn(async () => {
          throw new Error('LLM service unavailable');
        }),
        embed: jest.fn(async () => {
          throw new Error('LLM service unavailable');
        }),
      };

      agent.addNode('analyst', createAnalystNode(failingProvider));
      agent.setEntryPoint('analyst');

      const result = await agent.invoke('Test input');

      expect(result.summary.failedNodes).toBeGreaterThanOrEqual(1);
      expect(result.finalState.errors.length).toBeGreaterThan(0);
      expect(result.finalState.errors.some((e: string) => e.includes('LLM service unavailable'))).toBe(true);
    });

    it('should handle retry logic with transient provider failures', async () => {
      let callCount = 0;
      const flakyProvider: LLMProvider = {
        name: 'flaky',
        chat: jest.fn(async () => {
          callCount++;
          if (callCount < 3) throw new Error('Transient error');
          return { content: 'Success after retry', model: 'mock', provider: 'flaky' };
        }),
        embed: jest.fn(async () => ({ embeddings: [[]], model: 'mock', provider: 'flaky' })),
      };

      agent.setConfig({ maxRetries: 3, nodeTimeout: 1000 });
      agent.addNode('analyst', createAnalystNode(flakyProvider));
      agent.setEntryPoint('analyst');

      const result = await agent.invoke('Test retry');

      expect(result.summary.completedNodes).toBe(1);
      expect(result.finalState.outputs.analyst).toContain('Success after retry');
      expect(callCount).toBe(3);
    });

    it('should execute parallel reviewer+tester with provider', async () => {
      const provider = createMockProvider('ollama', 'Parallel node result');

      agent.addNode('programmer', createProgrammerNode());
      agent.addNode('parallel_reviewer_tester', createReviewerTesterParallelNode(provider));
      agent.addEdge('programmer', 'parallel_reviewer_tester');
      agent.addEdge('parallel_reviewer_tester', 'end');

      agent.setEntryPoint('programmer');

      const result = await agent.invoke('Generate code');

      expect(result.finalState.outputs.reviewer).toContain('Parallel node result');
      expect(result.finalState.outputs.tester).toContain('Parallel node result');
    });
  });
});