// import { ConfigManager } from '@ideia/config-engine';
// const config = ConfigManager.getInstance();

// Simple fallback config manager for build-time
const config = {
  get: (key: string): string | undefined => process.env[key]
};

export interface NatsEnvConfig {   servers: string;   streamName: string;   maxHistory: number;   reconnect: boolean;   maxReconnectAttempts: number;   reconnectTimeWait: number;   timeout: number;   token?: string;   user?: string;   pass?: string; }  export interface NatsConfigOverrides {   servers?: string | string[];   streamName?: string;   maxHistory?: number;   reconnect?: boolean;   maxReconnectAttempts?: number;   reconnectTimeWait?: number;   timeout?: number;   token?: string;   user?: string;   pass?: string; }  const DEFAULTS: NatsEnvConfig = {   servers: 'nats://localhost:4222',   streamName: 'ideia_events',   maxHistory: 10000,   reconnect: true,   maxReconnectAttempts: 10,   reconnectTimeWait: 2000,   timeout: 5000, };  function pickString(val: string | string[] | undefined, fallback: string): string {   if (Array.isArray(val)) return val[0] ?? fallback;   return val ?? fallback; }  export function loadNatsConfig(overrides?: NatsConfigOverrides): NatsEnvConfig {   return {     servers: config.get('NATS_SERVERS') ?? pickString(overrides?.servers, DEFAULTS.servers),     streamName: config.get('NATS_STREAM') ?? overrides?.streamName ?? DEFAULTS.streamName,     maxHistory: parseInt(config.get('NATS_MAX_HISTORY') ?? String(overrides?.maxHistory ?? DEFAULTS.maxHistory), 10),     reconnect: (config.get('NATS_RECONNECT') ?? String(overrides?.reconnect ?? DEFAULTS.reconnect)) === 'true',     maxReconnectAttempts: parseInt(config.get('NATS_MAX_RECONNECT') ?? String(overrides?.maxReconnectAttempts ?? DEFAULTS.maxReconnectAttempts), 10),     reconnectTimeWait: parseInt(config.get('NATS_RECONNECT_WAIT') ?? String(overrides?.reconnectTimeWait ?? DEFAULTS.reconnectTimeWait), 10),     timeout: parseInt(config.get('NATS_TIMEOUT') ?? String(overrides?.timeout ?? DEFAULTS.timeout), 10),     token: config.get('NATS_TOKEN') ?? overrides?.token,     user: config.get('NATS_USER') ?? overrides?.user,     pass: config.get('NATS_PASS') ?? overrides?.pass,   }; }  export function natsConfigToConnectionOptions(config: NatsEnvConfig): Record<string, unknown> {   const opts: Record<string, unknown> = {     servers: config.servers,     name: 'ideia-event-bus',     reconnect: config.reconnect,     maxReconnectAttempts: config.maxReconnectAttempts,     reconnectTimeWait: config.reconnectTimeWait,     timeout: config.timeout,   };   if (config.token) {     opts.token = config.token;   } else if (config.user && config.pass) {     opts.user = config.user;     opts.pass = config.pass;   }   return opts; }
