import { createLogger } from '@ideia/logger'
import { IAgent, AgentInput, AgentOutput, AgentRole, IntentInput, IntentOutput, PlanInput, PlanOutput, PlanStep, CodeInput, CodeOutput, CodeFile, CodeQuality, TestInput, TestOutput, TestResult, Ambiguity, RiskLevel } from './types'

const logger = createLogger('agent-specialization')

export class IntentAgent implements IAgent {
  role: AgentRole = 'intent'

  async execute(input: AgentInput): Promise<AgentOutput> {
    const start = Date.now()
    const data = input.data as IntentInput
    const intent: IntentOutput = {
      intent: data.rawText.slice(0, 200),
      objectives: [data.rawText.split('.')[0] || 'No clear objective'],
      scope: ['Implementation'],
      constraints: [],
      entities: this.extractEntities(data.rawText),
      ambiguities: this.detectAmbiguities(data.rawText),
      risk: this.estimateRisk(data.rawText),
    }
    const output: AgentOutput = {
      taskId: input.taskId, role: this.role, result: intent,
      confidence: intent.ambiguities.length > 2 ? 0.5 : 0.85,
      issues: intent.ambiguities.map(a => a.description), durationMs: Date.now() - start,
    }
    logger.info('IntentAgent executed', { taskId: input.taskId, confidence: output.confidence })
    return output
  }

  getCapabilities(): string[] { return ['intent-extraction', 'ambiguity-detection', 'entity-recognition', 'risk-estimation'] }

  private extractEntities(text: string): string[] {
    const entities: string[] = []
    const patterns = [/sistema/i, /usuário|usuario/i, /api/i, /banco\s*de\s*dados/i]
    for (const p of patterns) { if (p.test(text)) entities.push(p.source.replace(/\\/g, '').replace(/\/.*/g, '')) }
    return entities
  }

  private detectAmbiguities(text: string): Ambiguity[] {
    const result: Ambiguity[] = []
    if (/rápido|rapido|eficiente|melhor|fast|efficient|better|optimized|quick/i.test(text)) result.push({ type: 'metric', description: 'Vague metric term used', question: 'What specific metric defines success?' })
    if (/algum|vários|variosa|muitos|some|many|several|a lot/i.test(text)) result.push({ type: 'quantity', description: 'Unspecified quantity', question: 'What is the expected scale?' })
    return result
  }

  private estimateRisk(text: string): RiskLevel {
    const highRisk = /critical|critical|produção|producao|production/i.test(text)
    return highRisk ? 'high' as RiskLevel : 'medium' as RiskLevel
  }
}

export class PlanAgent implements IAgent {
  role: AgentRole = 'plan'

  async execute(input: AgentInput): Promise<AgentOutput> {
    const start = Date.now()
    const data = input.data as PlanInput
    const steps: PlanStep[] = data.availableAgents.map((agent, i) => ({
      id: `step-${i + 1}`, agent: agent as AgentRole, action: 'process',
      dependsOn: i > 0 ? [`step-${i}`] : [], estimatedTokens: 500, timeout: 60000,
    }))
    const plan: PlanOutput = {
      steps, estimatedDuration: steps.length * 60000,
      criticalPath: steps.map(s => s.id), risks: [],
    }
    const output: AgentOutput = {
      taskId: input.taskId, role: this.role, result: plan,
      confidence: 0.9, issues: [], durationMs: Date.now() - start,
    }
    logger.info('PlanAgent executed', { taskId: input.taskId, steps: steps.length })
    return output
  }

  getCapabilities(): string[] { return ['task-decomposition', 'scheduling', 'critical-path-analysis', 'risk-assessment'] }
}

export class CodeAgent implements IAgent {
  role: AgentRole = 'code'

  async execute(input: AgentInput): Promise<AgentOutput> {
    const start = Date.now()
    const data = input.data as CodeInput
    const files: CodeFile[] = [
      { path: 'src/index.ts', content: `// Generated by CodeAgent\n// Specification: ${data.specification.slice(0, 100)}`, language: data.language },
    ]
    const quality: CodeQuality = { score: 0.85, issues: ['Generated code requires review'], coverage: 0 }
    const output: CodeOutput = { files, quality, suggestions: ['Add error handling', 'Add input validation'] }
    logger.info('CodeAgent executed', { taskId: input.taskId, files: files.length })
    return { taskId: input.taskId, role: this.role, result: output, confidence: 0.8, issues: quality.issues, durationMs: Date.now() - start }
  }

  getCapabilities(): string[] { return ['code-generation', 'code-refactoring', 'code-review', 'error-handling'] }
}

export class TestAgent implements IAgent {
  role: AgentRole = 'test'

  async execute(input: AgentInput): Promise<AgentOutput> {
    const start = Date.now()
    const data = input.data as TestInput
    const testFiles: CodeFile[] = [{ path: 'tests/index.test.ts', content: `// Generated by TestAgent\nimport { describe, it, expect } from 'vitest'`, language: 'typescript' }]
    const testResults: TestResult[] = [{ suite: 'index', passed: true, total: 1, failed: 0, durationMs: 100 }]
    const output: TestOutput = { testFiles, testResults, coverage: 80 }
    logger.info('TestAgent executed', { taskId: input.taskId })
    return { taskId: input.taskId, role: this.role, result: output, confidence: 0.85, issues: [], durationMs: Date.now() - start }
  }

  getCapabilities(): string[] { return ['test-generation', 'test-execution', 'coverage-analysis', 'mutation-testing'] }
}
