apiVersion: v1
kind: Namespace
metadata:
  name: ideia
  labels:
    name: ideia
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ideia-staging
  labels:
    name: ideia-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ideia-dev
  labels:
    name: ideia-dev
    environment: development
