import { NpsResponse, NpsReport, NpsScore, SusResponse, SusReport, CesResponse, CesReport, CesScore, TimeToTaskRecord, TimeToTaskReport, PageLoadRecord, PageLoadReport, ErrorRecord, ErrorReport, SatisfactionRecord, SatisfactionReport, SatisfactionScore, AccessibilityRecord, AccessibilityReport, UxDashboard, UxAnalyticsConfig, PerformanceReport } from './types';
export declare function normalizeNps(score: number): number;
export declare class UxMetricsCollector {
    private npsResponses;
    private susResponses;
    private cesResponses;
    private timeToTaskRecords;
    private pageLoads;
    private errors;
    private satisfactionRecords;
    private a11yRecords;
    private config;
    private activeTimers;
    private db;
    constructor(config?: Partial<UxAnalyticsConfig>);
    getConfig(): UxAnalyticsConfig;
    initSqlite(dbPath?: string): void;
    private saveSqlite;
    private loadSqlite;
    save(filePath?: string): void;
    load(filePath?: string): boolean;
    static fromFile(filePath: string, config?: Partial<UxAnalyticsConfig>): UxMetricsCollector;
    recordNps(score: NpsScore, reason?: string): NpsResponse;
    getNpsReport(): NpsReport;
    normalizeNpsScore(score: NpsScore): number;
    recordSus(answers: number[]): SusResponse;
    getSusReport(): SusReport;
    recordCes(taskId: string, taskLabel: string, score: CesScore, durationMs: number): CesResponse;
    getCesReport(): CesReport;
    startTask(taskId: string, taskLabel: string): void;
    endTask(taskId: string): TimeToTaskRecord | null;
    getTimeToTaskReport(): TimeToTaskReport;
    recordPageLoad(url: string, loadTimeMs: number): PageLoadRecord;
    getPageLoadReport(): PageLoadReport;
    recordError(errorType: string, message: string): ErrorRecord;
    getErrorReport(): ErrorReport;
    getErrorRate(errorType?: string): number;
    recordSatisfaction(score: SatisfactionScore, context?: string): SatisfactionRecord;
    getSatisfactionReport(): SatisfactionReport;
    recordAccessibility(ruleId: string, score: number, violations: number, source: string): AccessibilityRecord;
    getAccessibilityReport(): AccessibilityReport;
    getDashboard(): UxDashboard;
    getAll(): {
        nps: NpsResponse[];
        sus: SusResponse[];
        ces: CesResponse[];
        timeToTask: TimeToTaskRecord[];
        pageLoads: PageLoadRecord[];
        errors: ErrorRecord[];
        satisfaction: SatisfactionRecord[];
        a11y: AccessibilityRecord[];
    };
    clear(): void;
    private perfMetrics;
    private optimisticOps;
    private loadingStartTimes;
    measurePageLoad(): number;
    measureInteraction<T>(interactionName: string, fn: () => Promise<T>): Promise<T>;
    measureRender<T>(componentName: string, renderFn: () => T): T;
    getPerformanceReport(): PerformanceReport;
    recordOptimistic(operation: string): void;
    getPerceivedPerformanceScore(): number;
    startLoading(operation: string): void;
    endLoading(operation: string): number;
}
export declare function createUxMetricsCollector(config?: Partial<UxAnalyticsConfig>): UxMetricsCollector;
//# sourceMappingURL=ux-metrics-collector.d.ts.map