import { createHash, randomBytes } from 'crypto';
import { createLogger } from '@ideia/logger';
import { type TLSConfig, type CACert, type ClientCert, type CertValidity } from './types';
const logger = createLogger('mtls-manager');

export class mTLSManager {
  private _caCerts: CACert[] = [];
  private _clientCerts: ClientCert[] = [];

  createDefaultConfig(overrides?: Partial<TLSConfig>): TLSConfig {
    return {
      enabled: true,
      certFile: '/etc/nats/certs/server.pem',
      keyFile: '/etc/nats/certs/server-key.pem',
      caFile: '/etc/nats/certs/ca.pem',
      verifyClient: true,
      mapCertToUser: true,
      handshakeTimeout: 5,
      minVersion: 'TLSv1.2',
      maxVersion: 'TLSv1.3',
      cipherSuites: [
        'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
        'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
        'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
        'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
        'TLS_AES_256_GCM_SHA384',
        'TLS_CHACHA20_POLY1305_SHA256',
      ],
      ecdhCurve: 'X25519:P-256:P-384',
      sessionTimeout: 300,
      sessionCacheSize: 10000,
      ...overrides,
    };
  }

  generateTLSConfigString(config: TLSConfig): string {
    const lines: string[] = [];
    lines.push('tls: {');
    if (config.certFile) lines.push(`  cert_file: "${config.certFile}"`);
    if (config.keyFile) lines.push(`  key_file: "${config.keyFile}"`);
    if (config.caFile) lines.push(`  ca_file: "${config.caFile}"`);
    lines.push(`  verify: ${config.verifyClient}`);
    lines.push(`  verify_and_map: ${config.mapCertToUser}`);
    lines.push(`  timeout: ${config.handshakeTimeout}`);
    if (config.minVersion) lines.push(`  min_version: "${config.minVersion}"`);
    if (config.maxVersion) lines.push(`  max_version: "${config.maxVersion}"`);
    if (config.cipherSuites && config.cipherSuites.length > 0) {
      lines.push('  cipher_suites: [');
      for (const cs of config.cipherSuites) {
        lines.push(`    ${cs},`);
      }
      lines.push('  ]');
    }
    if (config.ecdhCurve) lines.push(`  ecdh_curve: "${config.ecdhCurve}"`);
    if (config.sessionCacheSize !== undefined) lines.push(`  session_cache_size: ${config.sessionCacheSize}`);
    if (config.sessionTimeout !== undefined) lines.push(`  session_timeout: ${config.sessionTimeout}`);
    lines.push('}');
    return lines.join('\n');
  }

  generateNATSServerConfig(mTLSConfig: TLSConfig, additionalConfig?: Record<string, string>): string {
    const lines: string[] = [];
    lines.push('# IDEIA NATS Server Configuration');
    lines.push('# Generated by @ideia/nats-security/mTLSManager');
    lines.push('');
    lines.push(this.generateTLSConfigString(mTLSConfig));
    lines.push('');
    lines.push('authorization: {');
    lines.push('  timeout: 2.0');
    lines.push('}');
    if (additionalConfig) {
      lines.push('');
      for (const [key, value] of Object.entries(additionalConfig)) {
        lines.push(`${key}: ${value}`);
      }
    }
    return lines.join('\n');
  }

  addCACert(caCert: CACert): void {
    this._caCerts.push(caCert);
  }

  removeCACert(fingerprint: string): void {
    this._caCerts = this._caCerts.filter(c => c.fingerprint !== fingerprint);
  }

  getCACerts(): CACert[] {
    return [...this._caCerts];
  }

  parseCertificatePEM(pem: string): ClientCert {
    const fingerprint = createHash('sha256').update(pem).digest('hex');
    const cnMatch = pem.match(/CN\s*=\s*([^\n,]+)/);
    const commonName = cnMatch ? cnMatch[1].trim() : 'unknown';
    const serialMatch = pem.match(/Serial Number:\s*([^\n]+)/i);
    const serialNumber = serialMatch ? serialMatch[1].trim() : randomBytes(16).toString('hex');
    return {
      pem,
      commonName,
      issuer: 'IDEIA Internal CA',
      notBefore: Date.now() - 86400000,
      notAfter: Date.now() + 365 * 86400000,
      serialNumber,
      fingerprint,
    };
  }

  validateCertificate(clientCert: ClientCert, trustedCAs?: CACert[]): CertValidity {
    const now = Date.now();
    const certsToUse = trustedCAs ?? this._caCerts;
    const expiresInDays = Math.round((clientCert.notAfter - now) / 86400000);
    if (now > clientCert.notAfter) {
      return {
        valid: false,
        reason: 'Certificate has expired',
        expiresInDays: -1,
        notBeforeValid: now >= clientCert.notBefore,
        notAfterValid: false,
        issuerMatch: certsToUse.some(ca => clientCert.issuer.includes(ca.fingerprint.substring(0, 8))),
      };
    }
    if (now < clientCert.notBefore) {
      return {
        valid: false,
        reason: 'Certificate is not yet valid',
        expiresInDays,
        notBeforeValid: false,
        notAfterValid: true,
        issuerMatch: true,
      };
    }
    if (certsToUse.length > 0) {
      const issuerMatch = certsToUse.some(ca => {
        return clientCert.issuer.includes(ca.fingerprint.substring(0, 8));
      });
      if (!issuerMatch) {
        return {
          valid: false,
          reason: 'Certificate issuer not in trusted CA store',
          expiresInDays,
          notBeforeValid: true,
          notAfterValid: true,
          issuerMatch: false,
        };
      }
    }
    return {
      valid: true,
      expiresInDays,
      notBeforeValid: true,
      notAfterValid: true,
      issuerMatch: true,
    };
  }

  computeFingerprint(pem: string): string {
    return createHash('sha256').update(pem).digest('hex');
  }

  isMutualTLSRequired(config: TLSConfig): boolean {
    return config.enabled && config.verifyClient;
  }

  getTLSVersionRecommendation(): string {
    return 'TLSv1.3';
  }

  getRecommendedCiphers(): string[] {
    return [
      'TLS_AES_256_GCM_SHA384',
      'TLS_CHACHA20_POLY1305_SHA256',
      'TLS_AES_128_GCM_SHA256',
    ];
  }
}
