import { createLogger } from '@ideia/logger';
import {  type TenantConfig,
  type TenantUserConfig,
  type AccountLimits,
  type StreamExport,
  type StreamImport,
} from './types';
const logger = createLogger('multi-tenant-isolator');

export class MultiTenantIsolator {
  private _tenants: Map<string, TenantConfig> = new Map();
  private _defaultLimits: AccountLimits = {
    subs: 1000,
    data: -1,
    payload: -1,
    imports: 10,
    exports: 10,
  };

  createTenant(name: string, nkey: string, overrides?: Partial<TenantConfig>): TenantConfig {
    if (this._tenants.has(name)) {
      throw new Error(`Tenant "${name}" already exists`);
    }
    const config: TenantConfig = {
      name,
      nkey,
      signingKeys: overrides?.signingKeys ?? [],
      limits: { ...this._defaultLimits, ...overrides?.limits },
      exports: overrides?.exports ?? [],
      imports: overrides?.imports ?? [],
      users: overrides?.users ?? [],
    };
    this._tenants.set(name, config);
    return config;
  }

  removeTenant(name: string): boolean {
    return this._tenants.delete(name);
  }

  getTenant(name: string): TenantConfig | undefined {
    return this._tenants.get(name);
  }

  listTenants(): TenantConfig[] {
    return Array.from(this._tenants.values());
  }

  tenantExists(name: string): boolean {
    return this._tenants.has(name);
  }

  addUserToTenant(tenantName: string, user: TenantUserConfig): void {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      throw new Error(`Tenant "${tenantName}" not found`);
    }
    const existing = tenant.users.find(u => u.identity === user.identity);
    if (existing) {
      throw new Error(`User "${user.identity}" already exists in tenant "${tenantName}"`);
    }
    tenant.users.push(user);
  }

  removeUserFromTenant(tenantName: string, identity: string): boolean {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      return false;
    }
    const index = tenant.users.findIndex(u => u.identity === identity);
    if (index === -1) {
      return false;
    }
    tenant.users.splice(index, 1);
    return true;
  }

  addExport(tenantName: string, exp: StreamExport): void {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      throw new Error(`Tenant "${tenantName}" not found`);
    }
    const existing = tenant.exports.find(e => e.name === exp.name);
    if (existing) {
      throw new Error(`Export "${exp.name}" already exists in tenant "${tenantName}"`);
    }
    tenant.exports.push(exp);
  }

  removeExport(tenantName: string, exportName: string): boolean {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      return false;
    }
    const index = tenant.exports.findIndex(e => e.name === exportName);
    if (index === -1) {
      return false;
    }
    tenant.exports.splice(index, 1);
    return true;
  }

  addImport(tenantName: string, imp: StreamImport): void {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      throw new Error(`Tenant "${tenantName}" not found`);
    }
    const existing = tenant.imports.find(i => i.name === imp.name);
    if (existing) {
      throw new Error(`Import "${imp.name}" already exists in tenant "${tenantName}"`);
    }
    tenant.imports.push(imp);
  }

  removeImport(tenantName: string, importName: string): boolean {
    const tenant = this._tenants.get(tenantName);
    if (!tenant) {
      return false;
    }
    const index = tenant.imports.findIndex(i => i.name === importName);
    if (index === -1) {
      return false;
    }
    tenant.imports.splice(index, 1);
    return true;
  }

  connectAccounts(sourceTenant: string, targetTenant: string, subject: string): {
    exportDef: StreamExport;
    importDef: StreamImport;
  } {
    const source = this._tenants.get(sourceTenant);
    const target = this._tenants.get(targetTenant);
    if (!source) {
      throw new Error(`Source tenant "${sourceTenant}" not found`);
    }
    if (!target) {
      throw new Error(`Target tenant "${targetTenant}" not found`);
    }
    const exportDef: StreamExport = {
      name: `${subject}-export`,
      subject,
      type: 'stream',
      tokenReq: false,
      approvedAccounts: [targetTenant],
    };
    const importDef: StreamImport = {
      name: `${subject}-import`,
      subject,
      account: sourceTenant,
      type: 'stream',
    };
    source.exports.push(exportDef);
    target.imports.push(importDef);
    return { exportDef, importDef };
  }

  generateNATSConfig(): string {
    const lines: string[] = [];
    lines.push('// IDEIA Multi-Tenant NATS Configuration');
    lines.push('// Generated by @ideia/nats-security/MultiTenantIsolator');
    lines.push('');
    lines.push('accounts: {');
    for (const tenant of this._tenants.values()) {
      lines.push(`  ${tenant.name}: {`);
      if (tenant.exports.length > 0) {
        lines.push('    exports: [');
        for (const exp of tenant.exports) {
          const accounts = exp.approvedAccounts
            ? `accounts: [${exp.approvedAccounts.map(a => `"${a}"`).join(', ')}]`
            : '';
          lines.push(`      { ${exp.type}: "${exp.subject}", ${accounts} },`);
        }
        lines.push('    ]');
      }
      if (tenant.imports.length > 0) {
        lines.push('    imports: [');
        for (const imp of tenant.imports) {
          lines.push(`      { ${imp.type}: { account: "${imp.account}", subject: "${imp.subject}" } },`);
        }
        lines.push('    ]');
      }
      if (tenant.users.length > 0) {
        lines.push('    users: [');
        for (const user of tenant.users) {
          lines.push('      {');
          lines.push(`        user: "${user.identity}",`);
          lines.push('        permissions: {');
          const pubAllow = user.pubAllow.map(a => `"${a}"`).join(', ');
          const pubDeny = user.pubDeny.map(d => `"${d}"`).join(', ');
          const subAllow = user.subAllow.map(a => `"${a}"`).join(', ');
          const subDeny = user.subDeny.map(d => `"${d}"`).join(', ');
          lines.push(`          publish: { allow: [${pubAllow}], deny: [${pubDeny}] },`);
          lines.push(`          subscribe: { allow: [${subAllow}], deny: [${subDeny}] }`);
          lines.push('        }');
          lines.push('      },');
        }
        lines.push('    ]');
      }
      lines.push('  },');
    }
    lines.push('}');
    return lines.join('\n');
  }

  getTenantCount(): number {
    return this._tenants.size;
  }

  getUserCount(tenantName: string): number {
    const tenant = this._tenants.get(tenantName);
    return tenant ? tenant.users.length : 0;
  }

  getTotalUserCount(): number {
    let total = 0;
    for (const tenant of this._tenants.values()) {
      total += tenant.users.length;
    }
    return total;
  }
}
