import { PolicyRule, EventBus, PolicyEngine } from './types'
import { createLogger } from '@ideia/logger';
const logger = createLogger('policy-adapter');

export class PolicyAdapter {
  private _rules: Map<string, PolicyRule> = new Map()

  constructor(private _policyEngine: PolicyEngine, private _eventBus: EventBus) {}

  async applyRule(rule: PolicyRule): Promise<void> {
    const existing: PolicyRule | undefined = this._rules.get(rule.id)
    if (existing) {
      await this._policyEngine.updateRule(rule.id, this._toPolicyRuleFormat(rule))
    } else {
      await this._policyEngine.addRule(this._toPolicyRuleFormat(rule))
    }
    this._rules.set(rule.id, rule)
    await this._eventBus.publish('security.policy.rule_applied', {
      ruleId: rule.id,
      ruleType: rule.type,
      severity: rule.severity,
      timestamp: Date.now(),
    })
  }

  async removeRule(ruleId: string): Promise<void> {
    await this._policyEngine.removeRule(ruleId)
    this._rules.delete(ruleId)
    await this._eventBus.publish('security.policy.rule_removed', {
      ruleId,
      timestamp: Date.now(),
    })
  }

  async applyBatch(rules: PolicyRule[]): Promise<{ success: number; failed: number }> {
    let success = 0
    let failed = 0
    for (const rule of rules) {
      try {
        await this.applyRule(rule)
        success++
      } catch {
        failed++
      }
    }
    return { success, failed }
  }

  async getActiveRules(): Promise<PolicyRule[]> {
    return Array.from(this._rules.values())
  }

  private _toPolicyRuleFormat(rule: PolicyRule): Record<string, unknown> {
    return {
      id: rule.id,
      type: 'defense_auto',
      pattern: rule.pattern,
      action: rule.action,
      severity: rule.severity,
      source: rule.source,
      metadata: {
        createdAt: rule.createdAt,
        autoGenerated: true,
        attackType: rule.id,
      },
    }
  }
}
