import type { PrioritizedItem } from './prioritizer';
import { createLogger } from '@ideia/logger';
const logger = createLogger('action-handler');

export interface ActionResult {
  success: boolean;
  actionType: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface ActionHandlerOptions {
  createIssue?: (item: PrioritizedItem) => Promise<ActionResult>;
  generateTask?: (item: PrioritizedItem) => Promise<ActionResult>;
  respond?: (item: PrioritizedItem) => Promise<ActionResult>;
  autoRespond?: boolean;
  autoCreateIssues?: boolean;
  autoGenerateTasks?: boolean;
}

export class ActionHandler {
  private options: ActionHandlerOptions;

  constructor(options: ActionHandlerOptions = {}) {
    this.options = {
      autoRespond: options.autoRespond ?? false,
      autoCreateIssues: options.autoCreateIssues ?? false,
      autoGenerateTasks: options.autoGenerateTasks ?? false,
      createIssue: options.createIssue,
      generateTask: options.generateTask,
      respond: options.respond,
    };
  }

  async handle(item: PrioritizedItem): Promise<ActionResult[]> {
    const results: ActionResult[] = [];
    if (this.options.autoCreateIssues && this.options.createIssue) {
      results.push(await this.options.createIssue(item));
    }
    if (this.options.autoGenerateTasks && this.options.generateTask) {
      results.push(await this.options.generateTask(item));
    }
    if (this.options.autoRespond && this.options.respond) {
      results.push(await this.options.respond(item));
    }
    return results;
  }

  async createIssue(item: PrioritizedItem): Promise<ActionResult> {
    if (this.options.createIssue) {
      return this.options.createIssue(item);
    }
    const title = `[${item.priority.toUpperCase()}] ${item.feedback.content.slice(0, 72)}${item.feedback.content.length > 72 ? '...' : ''}`;
    return {
      success: true,
      actionType: 'create_issue',
      message: `Issue created: ${title}`,
      details: { title, feedbackId: item.feedback.id, priority: item.priority },
    };
  }

  async generateTask(item: PrioritizedItem): Promise<ActionResult> {
    if (this.options.generateTask) {
      return this.options.generateTask(item);
    }
    return {
      success: true,
      actionType: 'generate_task',
      message: `Task generated from feedback ${item.feedback.id}`,
      details: { feedbackId: item.feedback.id, priority: item.priority, targetType: item.feedback.targetType, targetId: item.feedback.targetId },
    };
  }

  async respond(item: PrioritizedItem): Promise<ActionResult> {
    if (this.options.respond) {
      return this.options.respond(item);
    }
    const response = `Thank you for your ${item.classification?.category ?? 'feedback'}. We have ${item.priority === 'critical' ? 'immediately' : 'logged'} your ${item.feedback.type} regarding ${item.feedback.targetType}:${item.feedback.targetId}.`;
    return {
      success: true,
      actionType: 'respond',
      message: response,
      details: { feedbackId: item.feedback.id, priority: item.priority, autoGenerated: true },
    };
  }
}
