export interface AccountConfig {
  name: string;
  nkey: string;
  limits: { subs: number; data: number; payload: number; imports: number; exports: number };
  exports: Array<{ stream: string; accounts: string[] } | { service: string; accounts: string[] }>;
  imports: Array<{ stream: { account: string; subject: string } } | { service: { account: string; subject: string } }>;
  users: Array<{ name: string; pubAllow: string[]; pubDeny: string[]; subAllow: string[]; subDeny: string[] }>;
}

export interface TenantConfig {
  operatorName: string;
  operatorNkey: string;
  accountServerUrl: string;
  accounts: AccountConfig[];
}

export class MultiTenantConfig {
  generateNatsConfig(config: TenantConfig): string {
    const lines: string[] = [];
    lines.push('// IDEIA Multi-Tenant NATS Configuration');
    lines.push('// Generated by @ideia/nats-auth');
    lines.push('');
    lines.push('operator: {');
    lines.push(`  operator_name: "${config.operatorName}"`);
    lines.push('}');
    lines.push('');
    lines.push('accounts: {');

    for (const acct of config.accounts) {
      lines.push(`  ${acct.name}: {`);
      if (acct.exports.length > 0) {
        lines.push('    exports: [');
        for (const exp of acct.exports) {
          if ('stream' in exp) {
            lines.push(`      { stream: "${exp.stream}", accounts: [${exp.accounts.map(a => `"${a}"`).join(', ')}] },`);
          } else {
            lines.push(`      { service: "${exp.service}", accounts: [${exp.accounts.map(a => `"${a}"`).join(', ')}] },`);
          }
        }
        lines.push('    ]');
      }
      if (acct.imports.length > 0) {
        lines.push('    imports: [');
        for (const imp of acct.imports) {
          if ('stream' in imp) {
            lines.push(`      { stream: { account: "${imp.stream.account}", subject: "${imp.stream.subject}" } },`);
          } else {
            lines.push(`      { service: { account: "${imp.service.account}", subject: "${imp.service.subject}" } },`);
          }
        }
        lines.push('    ]');
      }
      lines.push('    users: [');
      for (const user of acct.users) {
        lines.push('      {');
        lines.push(`        user: "${user.name}",`);
        lines.push('        permissions: {');
        lines.push(`          publish: { allow: [${user.pubAllow.map(a => `"${a}"`).join(', ')}], deny: [${user.pubDeny.map(d => `"${d}"`).join(', ')}] },`);
        lines.push(`          subscribe: { allow: [${user.subAllow.map(a => `"${a}"`).join(', ')}], deny: [${user.subDeny.map(d => `"${d}"`).join(', ')}] }`);
        lines.push('        }');
        lines.push('      },');
      }
      lines.push('    ]');
      lines.push('  },');
    }

    lines.push('}');
    return lines.join('\n');
  }
}
