import { createLogger } from '@ideia/logger'
import { OpenAPIObject, GeneratorConfig, EndpointDef, GeneratedSDK } from './types'

const log = createLogger('api-sdk-generator')

export class APISDKGenerator {
  generate(config: GeneratorConfig): GeneratedSDK {
    const endpoints = this._extractEndpoints(config.spec)
    const types = this._generateTypes(endpoints, config.spec, config.language)
    const client = this._generateClientCode(endpoints, config)
    const hooks = config.includeReactHooks ? this._generateReactHooks(endpoints) : ''
    const tests = config.generateTests ? this._generateTests(endpoints) : ''

    const files: Array<{ path: string; content: string }> = [
      { path: 'types.ts', content: types },
      { path: 'client.ts', content: client },
    ]
    if (hooks) files.push({ path: 'hooks.ts', content: hooks })
    if (tests) files.push({ path: 'client.test.ts', content: tests })

    const typeCount = types.split('\n').filter(l => l.includes('interface') || l.includes('type ')).length
    log.info(`Generated SDK: ${endpoints.length} endpoints, ${typeCount} types`)
    return { files, stats: { endpointCount: endpoints.length, typeCount } }
  }

  private _extractEndpoints(spec: OpenAPIObject): EndpointDef[] {
    const endpoints: EndpointDef[] = []
    const paths = spec.paths || {}
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, def] of Object.entries(methods as any)) {
        if (!['get', 'post', 'put', 'delete', 'patch'].includes(method)) continue
        const opId = (def as any).operationId || `${method}_${path.replace(/[\/{}]/g, '_')}`
        endpoints.push({
          method: method.toUpperCase(),
          path,
          operationId: opId,
          params: this._extractParams(path, def as any),
          requestBody: this._extractRequestBody(def as any),
          response: this._extractResponse(def as any),
          summary: (def as any).summary || '',
        })
      }
    }
    return endpoints
  }

  private _generateTypes(_endpoints: EndpointDef[], spec: OpenAPIObject, language: string): string {
    const schemas = (spec.components?.schemas || {}) as Record<string, any>
    let output = '// Auto-generated by IDEIA APISDKGenerator\n\n'
    if (language === 'typescript') {
      for (const [name, schema] of Object.entries(schemas)) {
        const props = Object.entries(schema.properties || {}).map(([key, prop]: [string, any]) =>
          `  ${key}${schema.required?.includes(key) ? '' : '?'}: ${this._tsTypeFromSchema(prop)};`)
        output += `export interface ${name} {\n${props.join('\n')}\n}\n\n`
      }
    }
    return output
  }

  private _tsTypeFromSchema(prop: any): string {
    if (prop.$ref) return prop.$ref.split('/').pop() || 'unknown'
    if (prop.type === 'array') return `${this._tsTypeFromSchema(prop.items || { type: 'unknown' })}[]`
    const map: Record<string, string> = { string: 'string', integer: 'number', number: 'number', boolean: 'boolean', object: 'Record<string, unknown>' }
    return map[prop.type] || 'unknown'
  }

  private _generateClientCode(endpoints: EndpointDef[], config: GeneratorConfig): string {
    if (config.language !== 'typescript') return ''
    const operationIds = endpoints.map(ep => `${ep.operationId}Params, ${ep.operationId}Response`)
    let code = `import type { ${operationIds.join(', ')} } from './types';\n\nexport class ApiClient {\n  constructor(private baseUrl: string, private headers?: Record<string, string>) {}\n\n`
    for (const ep of endpoints) {
      let path = ep.path
      for (const p of ep.params.filter(p => p.in === 'path')) {
        path = path.replace(`{${p.name}}`, `\${params.${p.name}}`)
      }
      code += `  async ${ep.operationId}(params: ${ep.operationId}Params): Promise<${ep.operationId}Response> {\n`
      code += `    const res = await fetch(\`\${this.baseUrl}${path}\`, { method: '${ep.method}', headers: { 'Content-Type': 'application/json', ...this.headers }${ep.requestBody ? ',\n    body: JSON.stringify(params.body)' : ''} });\n`
      code += `    if (!res.ok) throw new Error('API Error');\n    return res.json();\n  }\n\n`
    }
    return code + '}\n'
  }

  private _generateReactHooks(endpoints: EndpointDef[]): string {
    let code = 'import { useState, useEffect } from "react";\nimport { ApiClient } from "./client";\n\n'
    for (const ep of endpoints.slice(0, 5)) {
      code += `export function use${ep.operationId.charAt(0).toUpperCase() + ep.operationId.slice(1)}(params: any) {\n`
      code += '  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n'
      code += '  useEffect(() => { new ApiClient("").' + ep.operationId + '(params).then(setData).finally(() => setLoading(false)); }, []);\n'
      code += '  return { data, loading };\n}\n\n'
    }
    return code
  }

  private _generateTests(endpoints: EndpointDef[]): string {
    let code = 'import { ApiClient } from "./client";\n\n'
    for (const ep of endpoints.slice(0, 3)) {
      code += `describe('${ep.operationId}', () => {\n`
      code += '  it(`should call ${ep.method} ${ep.path}`, async () => {\n'
      code += '    const client = new ApiClient("http://localhost:3000");\n'
      code += '    const result = await client.' + ep.operationId + '({} as any);\n'
      code += '    expect(result).toBeDefined();\n  });\n});\n\n'
    }
    return code
  }

  private _extractParams(path: string, def: any): Array<{ name: string; in: string; required: boolean; schema: any }> {
    const params = [...(def.parameters || [])]
    for (const pp of (path.match(/\{(\w+)\}/g) || []).map(p => p.slice(1, -1))) {
      if (!params.find((p: any) => p.name === pp)) params.push({ name: pp, in: 'path', required: true, schema: { type: 'string' } })
    }
    return params
  }

  private _extractRequestBody(def: any): any {
    return def.requestBody?.content?.['application/json']?.schema
  }

  private _extractResponse(def: any): any {
    return def.responses?.['200']?.content?.['application/json']?.schema ||
      def.responses?.['201']?.content?.['application/json']?.schema
  }
}
