import * as fs from 'fs';
import * as path from 'path';
import { createLogger } from '@ideia/logger';
import { EventBus } from '@ideia/event-bus';
import { AdrDecision, AdrStatus } from './types';
import { AdrTemplate, AdrTemplateData, AdrTemplateType } from './adr-template';

export interface AdrGenerateOptions {
  adrDir?: string;
  autoGenerate?: boolean;
  enableGitCommit?: boolean;
}

function padId(n: number): string {
  return String(n).padStart(4, '0');
}

function adrFilename(id: string, title: string): string {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `ADR-${id}-${slug}.md`;
}

function tryGitCommit(filePath: string, title: string, id: string): boolean {
  try {
    const { execSync } = require('child_process');
    execSync(`git add "${filePath}"`, { cwd: process.cwd() });
    execSync(`git commit -m "docs(adr): ${title} [ADR-${id}]" --no-verify`, { cwd: process.cwd() });
    return true;
  } catch {
    return false;
  }
}

export class AdrGenerator {
  private template: AdrTemplate;
  private adrDir: string;
  private bus?: EventBus;
  private enableGitCommit: boolean;
  private logger = createLogger('adr-generator');

  constructor(bus?: EventBus, options?: AdrGenerateOptions) {
    this.template = new AdrTemplate();
    this.adrDir = options?.adrDir ?? path.join(process.cwd(), 'docs', 'adr');
    this.bus = bus;
    this.enableGitCommit = options?.enableGitCommit ?? false;
    fs.mkdirSync(this.adrDir, { recursive: true });
  }

  async generateADR(
    decision: string,
    context: string,
    options: {
      title: string;
      status?: AdrStatus;
      consequences?: string[];
      compliance?: string;
      autoGenerate?: boolean;
      templateType?: AdrTemplateType;
    },
  ): Promise<AdrDecision> {
    const nextId = await this.nextId();
    const id = padId(nextId);
    const date = new Date().toISOString().split('T')[0];
    const status = options.status ?? 'proposed';
    const consequences = options.consequences ?? [decision];

    const data: AdrTemplateData = {
      id,
      title: options.title,
      status,
      date,
      context,
      decision,
      consequences,
      compliance: options.compliance,
      templateType: options.templateType,
    };

    const content = this.template.render(data);
    const filePath = path.join(this.adrDir, adrFilename(id, options.title));
    fs.writeFileSync(filePath, content, 'utf-8');

    const adr: AdrDecision = {
      id,
      title: options.title,
      status: status as AdrStatus,
      date,
      context,
      decision,
      consequences,
      autoGenerated: options.autoGenerate ?? false,
    };

    this.logger.info(`Generated ADR ${id}: ${options.title} → ${filePath}`);

    if (this.enableGitCommit) {
      tryGitCommit(filePath, options.title, id);
    }

    if (this.bus) {
      await this.bus.emit({
        type: 'adr.generated',
        source: 'adr-generator',
        payload: { adr, filePath },
      });
    }

    return adr;
  }

  async listADRs(): Promise<AdrDecision[]> {
    if (!fs.existsSync(this.adrDir)) return [];

    const entries = fs.readdirSync(this.adrDir);
    const results: AdrDecision[] = [];

    for (const entry of entries) {
      if (!entry.startsWith('ADR-') || !entry.endsWith('.md')) continue;
      const idMatch = entry.match(/^ADR-(\w+)-/);
      if (!idMatch) continue;

      const content = fs.readFileSync(path.join(this.adrDir, entry), 'utf-8');
      const parsed = this.parseAdrFile(content, idMatch[1]);
      if (parsed) results.push(parsed);
    }

    return results.sort((a, b) => parseInt(a.id) - parseInt(b.id));
  }

  private parseAdrFile(content: string, id: string): AdrDecision | null {
    try {
      const titleMatch = content.match(/^# ADR \w+: (.+)$/m);
      const statusMatch = content.match(/\*\*Status:\*\* (.+?)(?: {2}|$)/m);
      const dateMatch = content.match(/\*\*Date:\*\* (.+?)(?: {2}|$)/m);
      const contextMatch = content.match(/## Context\n\n([\s\S]*?)\n\n## Decision/);
      const decisionMatch = content.match(/## Decision\n\n([\s\S]*?)\n\n## Consequences/);
      const consequencesMatch = content.match(/## Consequences\n\n([\s\S]*?)(?:\n\n## |\n\n> Superseded|$)/);

      if (!titleMatch || !statusMatch || !dateMatch || !contextMatch || !decisionMatch || !consequencesMatch) {
        return null;
      }

      const consequences = consequencesMatch[1]
        .split('\n')
        .map(l => l.replace(/^- /, '').trim())
        .filter(Boolean);

      return {
        id,
        title: titleMatch[1].trim(),
        status: statusMatch[1].trim() as AdrStatus,
        date: dateMatch[1].trim(),
        context: contextMatch[1].trim(),
        decision: decisionMatch[1].trim(),
        consequences,
      };
    } catch {
      return null;
    }
  }

  private async nextId(): Promise<number> {
    const existing = await this.listADRs();
    if (existing.length === 0) return 1;
    const maxId = Math.max(...existing.map(a => parseInt(a.id)));
    return maxId + 1;
  }
}
