export type AdrStatus = 'proposed' | 'accepted' | 'deprecated' | 'superseded';

export interface AdrFormatData {
  id: string;
  title: string;
  status: AdrStatus;
  date: string;
  context: string;
  decision: string;
  consequences: string[];
  compliance?: string;
  supersededBy?: string;
  autoGenerated?: boolean;
}

export class AdrFormat {
  render(data: AdrFormatData): string {
    const lines: string[] = [];
    lines.push(`# ADR ${data.id}: ${data.title}`);
    lines.push('');
    lines.push(`* **Status:** ${data.status}`);
    lines.push(`* **Date:** ${data.date}`);
    if (data.autoGenerated) {
      lines.push(`* **Auto-generated:** true`);
    }
    if (data.compliance) {
      lines.push(`* **Compliance:** ${data.compliance}`);
    }
    lines.push('');
    lines.push('## Context');
    lines.push('');
    lines.push(data.context);
    lines.push('');
    lines.push('## Decision');
    lines.push('');
    lines.push(data.decision);
    lines.push('');
    lines.push('## Consequences');
    lines.push('');
    for (const c of data.consequences) {
      lines.push(`- ${c}`);
    }
    if (data.supersededBy) {
      lines.push('');
      lines.push(`> Superseded by ADR ${data.supersededBy}`);
    }
    lines.push('');
    lines.push('---');
    lines.push(`*ADR ${data.id} automatically formatted by IDEIA Auto-ADR*`);
    lines.push('');
    return lines.join('\n');
  }

  renderMadr(data: AdrFormatData): string {
    const lines: string[] = [];
    lines.push(`# ${data.id} — ${data.title}`);
    lines.push('');
    lines.push(`- **Status:** ${data.status}`);
    lines.push(`- **Date:** ${data.date}`);
    lines.push('');
    lines.push(`## Context`);
    lines.push('');
    lines.push(data.context);
    lines.push('');
    lines.push(`## Decision`);
    lines.push('');
    lines.push(data.decision);
    lines.push('');
    lines.push(`## Consequences`);
    lines.push('');
    for (const c of data.consequences) {
      lines.push(`- ${c}`);
    }
    lines.push('');
    return lines.join('\n');
  }

  getTemplate(): string {
    return [
      '# ADR {id}: {title}',
      '',
      '* **Status:** {status}',
      '* **Date:** {date}',
      '',
      '## Context',
      '',
      '{context}',
      '',
      '## Decision',
      '',
      '{decision}',
      '',
      '## Consequences',
      '',
      '- {consequence}',
      '',
      '## Compliance',
      '',
      '{compliance}',
      '',
    ].join('\n');
  }

  parse(content: string): AdrFormatData | null {
    try {
      const titleMatch = content.match(/^# ADR (\w+): (.+)$/m);
      const statusMatch = content.match(/\*\*Status:\*\* (.+?)(?: {2}|$)/m) || content.match(/\* \*\*Status:\*\* (.+)$/m);
      const dateMatch = content.match(/\*\*Date:\*\* (.+?)(?: {2}|$)/m) || content.match(/\* \*\*Date:\*\* (.+)$/m);
      const contextMatch = content.match(/## Context\n\n([\s\S]*?)\n\n## Decision/);
      const decisionMatch = content.match(/## Decision\n\n([\s\S]*?)\n\n## Consequences/);
      const consequencesMatch = content.match(/## Consequences\n\n([\s\S]*?)(?:\n\n## |\n\n> Superseded|$)/);
      const supersededMatch = content.match(/> Superseded by ADR (\w+)/);
      const autoMatch = content.match(/\*\*Auto-generated:\*\* true/);

      if (!titleMatch || !statusMatch || !dateMatch || !contextMatch || !decisionMatch || !consequencesMatch) {
        return null;
      }

      const consequences = consequencesMatch[1].split('\n').map(l => l.replace(/^- /, '').trim()).filter(Boolean);

      return {
        id: titleMatch[1],
        title: titleMatch[2].trim(),
        status: statusMatch[1].trim() as AdrStatus,
        date: dateMatch[1].trim(),
        context: contextMatch[1].trim(),
        decision: decisionMatch[1].trim(),
        consequences,
        supersededBy: supersededMatch ? supersededMatch[1] : undefined,
        autoGenerated: autoMatch !== null,
      };
    } catch {
      return null;
    }
  }

  filename(id: string, title: string): string {
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    return `ADR-${id}-${slug}.md`;
  }

  padId(n: number): string {
    return String(n).padStart(4, '0');
  }
}

export function createAdrFormat(): AdrFormat {
  return new AdrFormat();
}
