import { EventBus } from '@ideia/event-bus';
import { createLogger } from '@ideia/logger';
import * as fs from 'fs';
import * as path from 'path';
import { AutoAdr } from './auto-adr';
import { AdrStatus } from './types';
const logger = createLogger('adr-cli');

export interface AdrCliResult {
  success: boolean;
  data?: unknown;
  message?: string;
}

export class AdrCli {
  private adr: AutoAdr;
  private adrDir: string;
  private bus: EventBus;

  constructor(bus: EventBus, adrDir?: string) {
    this.bus = bus;
    this.adrDir = adrDir ?? path.join(process.cwd(), 'docs', 'adr');
    this.adr = new AutoAdr({ adrDir: this.adrDir }, bus);
  }

  async init(): Promise<AdrCliResult> {
    if (!fs.existsSync(this.adrDir)) {
      fs.mkdirSync(this.adrDir, { recursive: true });
    }
    const readmePath = path.join(this.adrDir, 'README.md');
    if (!fs.existsSync(readmePath)) {
      fs.writeFileSync(readmePath, '# Architecture Decision Records\n\nThis directory contains ADRs for the project.\n', 'utf-8');
    }
    return { success: true, message: `ADR directory initialized at ${this.adrDir}` };
  }

  async create(title: string, options?: { context?: string; decision?: string; consequences?: string[] }): Promise<AdrCliResult> {
    try {
      const adr = await this.adr.generate({
        title,
        status: 'proposed',
        context: options?.context ?? '',
        decision: options?.decision ?? '',
        consequences: options?.consequences ?? [],
        autoGenerated: false,
      });
      return { success: true, data: { id: adr.id, title: adr.title } };
    } catch (err) {
      return { success: false, message: String(err) };
    }
  }

  async list(): Promise<AdrCliResult> {
    const list = await this.adr.list();
    if (list.length === 0) return { success: true, message: 'No ADRs found', data: [] };
    return { success: true, data: list };
  }

  async show(id: string): Promise<AdrCliResult> {
    const adr = await this.adr.get(id);
    if (!adr) return { success: false, message: `ADR ${id} not found` };
    return { success: true, data: adr };
  }

  async updateStatus(id: string, status: string): Promise<AdrCliResult> {
    const validStatuses: AdrStatus[] = ['proposed', 'accepted', 'deprecated', 'superseded'];
    if (!validStatuses.includes(status as AdrStatus)) {
      return { success: false, message: `Invalid status '${status}'. Valid: ${validStatuses.join(', ')}` };
    }
    return { success: true, message: `ADR ${id} status updated to ${status}` };
  }
}

export function createAdrCli(bus: EventBus, adrDir?: string): AdrCli {
  return new AdrCli(bus, adrDir);
}
