import fsp from 'fs/promises';
import fs from 'fs';
import path from 'path';
import _crypto from 'crypto';
import { createLogger } from '@ideia/logger';
import { EventBus } from '@ideia/event-bus';
import { AdrDecision, AdrStatus, AutoAdrConfig } from './types';

const log = createLogger('auto-adr');

function padId(n: number): string {
  return String(n).padStart(4, '0');
}

function adrFilename(id: string, title: string): string {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `ADR-${id}-${slug}.md`;
}

function renderAdrMarkdown(d: AdrDecision): string {
  const lines: string[] = [];
  lines.push(`# ADR ${d.id}: ${d.title}`);
  lines.push('');
  lines.push(`**Status:** ${d.status}  `);
  lines.push(`**Date:** ${d.date}  `);
  if (d.autoGenerated) {
    lines.push('**Auto-generated:** true  ');
  }
  lines.push('');
  lines.push('## Context');
  lines.push('');
  lines.push(d.context);
  lines.push('');
  lines.push('## Decision');
  lines.push('');
  lines.push(d.decision);
  lines.push('');
  lines.push('## Consequences');
  lines.push('');
  for (const c of d.consequences) {
    lines.push(`- ${c}`);
  }
  if (d.supersededBy) {
    lines.push('');
    lines.push(`> Superseded by ADR ${d.supersededBy}`);
  }
  lines.push('');
  return lines.join('\n');
}

function parseAdrMarkdown(content: string, id: string): AdrDecision | null {
  try {
    const titleMatch = content.match(/^# ADR \w+: (.+)$/m);
    const statusMatch = content.match(/\*\*Status:\*\* (.+?)(?: {2}|$)/m);
    const dateMatch = content.match(/\*\*Date:\*\* (.+?)(?: {2}|$)/m);
    const contextMatch = content.match(/## Context\n\n([\s\S]*?)\n\n## Decision/);
    const decisionMatch = content.match(/## Decision\n\n([\s\S]*?)\n\n## Consequences/);
    const consequencesMatch = content.match(/## Consequences\n\n([\s\S]*?)(?:\n\n> Superseded|$)/);
    const supersededMatch = content.match(/> Superseded by ADR (\w+)/);
    const autoMatch = content.match(/\*\*Auto-generated:\*\* true/);

    if (!titleMatch || !statusMatch || !dateMatch || !contextMatch || !decisionMatch || !consequencesMatch) return null;

    const consequences = consequencesMatch[1].split('\n').map(l => l.replace(/^- /, '').trim()).filter(Boolean);

    return {
      id,
      title: titleMatch[1].trim(),
      status: statusMatch[1].trim() as AdrStatus,
      date: dateMatch[1].trim(),
      context: contextMatch[1].trim(),
      decision: decisionMatch[1].trim(),
      consequences,
      supersededBy: supersededMatch ? supersededMatch[1] : undefined,
      autoGenerated: autoMatch !== null,
    };
  } catch (_err) {
    log.error('Failed to parse ADR markdown', { id, error: String(_err) });
    return null;
  }
}

export class AutoAdr {
  private config: AutoAdrConfig;
  private bus: EventBus;

  constructor(config: Partial<AutoAdrConfig>, bus: EventBus) {
    this.config = {
      adrDir: config.adrDir ?? path.join(process.cwd(), 'docs', 'adr'),
      autoApproveThreshold: config.autoApproveThreshold ?? 3,
    };
    this.bus = bus;
    fs.mkdirSync(this.config.adrDir, { recursive: true });
  }

  async generate(decision: Omit<AdrDecision, 'id' | 'date'>): Promise<AdrDecision> {
    const nextId = await this.nextId();
    const full: AdrDecision = {
      ...decision,
      id: padId(nextId),
      date: new Date().toISOString().split('T')[0],
    };
    const filePath = path.join(this.config.adrDir, adrFilename(full.id, full.title));
    const content = renderAdrMarkdown(full);
    await fsp.writeFile(filePath, content, 'utf-8');
    log.info(`ADR ${full.id} generated`, { file: filePath });
    await this.bus.emit({ type: 'self.adr.generated', source: 'auto-adr', payload: { adr: full, filePath } });
    return full;
  }

  async list(): Promise<AdrDecision[]> {
    const entries = await fsp.readdir(this.config.adrDir);
    const results: AdrDecision[] = [];
    for (const entry of entries) {
      if (!entry.startsWith('ADR-') || !entry.endsWith('.md')) continue;
      const idMatch = entry.match(/^ADR-(\w+)-/);
      if (!idMatch) continue;
      const content = await fsp.readFile(path.join(this.config.adrDir, entry), 'utf-8');
      const parsed = parseAdrMarkdown(content, idMatch[1]);
      if (parsed) results.push(parsed);
    }
    return results.sort((a, b) => parseInt(a.id) - parseInt(b.id));
  }

  async get(id: string): Promise<AdrDecision | null> {
    const entries = await fsp.readdir(this.config.adrDir);
    for (const entry of entries) {
      if (entry.startsWith(`ADR-${id}-`) && entry.endsWith('.md')) {
        const content = await fsp.readFile(path.join(this.config.adrDir, entry), 'utf-8');
        return parseAdrMarkdown(content, id);
      }
    }
    return null;
  }

  async supersede(id: string, newId: string): Promise<AdrDecision | null> {
    const existing = await this.get(id);
    if (!existing) return null;

    const newAdr = await this.get(newId);
    if (!newAdr) return null;

    existing.status = 'superseded';
    existing.supersededBy = newId;
    const filePath = path.join(this.config.adrDir, adrFilename(existing.id, existing.title));
    await fsp.writeFile(filePath, renderAdrMarkdown(existing), 'utf-8');

    await this.bus.emit({ type: 'self.adr.generated', source: 'auto-adr', payload: { action: 'superseded', oldId: id, newId } });
    return existing;
  }

  private async nextId(): Promise<number> {
    const existing = await this.list();
    if (existing.length === 0) return 1;
    const maxId = Math.max(...existing.map(a => parseInt(a.id)));
    return maxId + 1;
  }
}

export function createAutoAdr(bus: EventBus, config?: Partial<AutoAdrConfig>): AutoAdr {
  return new AutoAdr(config ?? {}, bus);
}
