import { createLogger } from '@ideia/logger';
import { EventBus } from '@ideia/event-bus';
import { AutoAdr } from './auto-adr';

const log = createLogger('auto-adr-integration');

export interface AutoFixEvent {
  fixId: string;
  filePath: string;
  description: string;
  changeType: 'refactor' | 'bugfix' | 'optimization' | 'security' | 'style' | 'documentation';
  beforeSnippet?: string;
  afterSnippet?: string;
  appliedAt: string;
  appliedBy: string;
  context?: Record<string, unknown>;
}

export class AutoAdrIntegration {
  private autoAdr: AutoAdr;
  private bus: EventBus;
  private subscriptionIds: string[] = [];

  constructor(autoAdr: AutoAdr, bus: EventBus) {
    this.autoAdr = autoAdr;
    this.bus = bus;
  }

  async start(): Promise<void> {
    const subId = await this.bus.subscribe('self.fix.applied', (event: any) => {
      const payload = event.payload as Record<string, unknown> | undefined;
      if (!payload) return;
      const fixEvent: AutoFixEvent = {
        fixId: (payload.fixId as string) ?? 'unknown',
        filePath: (payload.filePath as string) ?? '',
        description: (payload.description as string) ?? 'Auto-fix applied',
        changeType: (payload.changeType as AutoFixEvent['changeType']) ?? 'refactor',
        appliedAt: (payload.appliedAt as string) ?? new Date().toISOString(),
        appliedBy: (payload.appliedBy as string) ?? 'auto-fix',
        context: payload.context as Record<string, unknown> | undefined,
      };
      this.generateAdrFromFix(fixEvent).catch((err) => {
        log.error('Failed to generate ADR from fix', { fixId: fixEvent.fixId, error: String(err) });
      });
    });
    this.subscriptionIds.push(subId);
  }

  async stop(): Promise<void> {
    for (const id of this.subscriptionIds) {
      await this.bus.unsubscribe(id);
    }
    this.subscriptionIds = [];
  }

  async generateAdrFromFix(fix: AutoFixEvent): Promise<string> {
    const title = `Auto-fix: ${fix.description.slice(0, 60)}`;
    const context = `An auto-fix was applied to ${fix.filePath} by ${fix.appliedBy}.\n\nType: ${fix.changeType}\nDescription: ${fix.description}`;
    const decision = `Applied fix ${fix.fixId} to ${fix.filePath}:\n- Change type: ${fix.changeType}\n- File: ${fix.filePath}\n- Description: ${fix.description}`;
    const consequences = [
      `Auto-fix applied to ${fix.filePath}`,
      `Change type: ${fix.changeType}`,
      `Applied by: ${fix.appliedBy}`,
    ];
    if (fix.changeType === 'security') {
      consequences.push('Security-related change — verify no regression');
    }
    if (fix.changeType === 'refactor') {
      consequences.push('Refactoring — verify behavior preservation');
    }

    const adr = await this.autoAdr.generate({
      title,
      status: 'accepted',
      context,
      decision,
      consequences,
      autoGenerated: true,
    });
    log.info('ADR generated from auto-fix', { adrId: adr.id, fixId: fix.fixId });
    return adr.id;
  }

  async generateAdrFromSelfFix(fixId: string, filePath: string, description: string): Promise<string> {
    return this.generateAdrFromFix({
      fixId,
      filePath,
      description,
      changeType: 'refactor',
      appliedAt: new Date().toISOString(),
      appliedBy: 'self-optimization',
    });
  }
}

export function createAutoAdrIntegration(autoAdr: AutoAdr, bus: EventBus): AutoAdrIntegration {
  return new AutoAdrIntegration(autoAdr, bus);
}
