"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoAdr = void 0;
exports.createAutoAdr = createAutoAdr;
const promises_1 = __importDefault(require("fs/promises"));
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
const logger_1 = require("@ideia/logger");
const log = (0, logger_1.createLogger)('auto-adr');
function padId(n) {
    return String(n).padStart(4, '0');
}
function adrFilename(id, title) {
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    return `ADR-${id}-${slug}.md`;
}
function renderAdrMarkdown(d) {
    const lines = [];
    lines.push(`# ADR ${d.id}: ${d.title}`);
    lines.push('');
    lines.push(`**Status:** ${d.status}  `);
    lines.push(`**Date:** ${d.date}  `);
    if (d.autoGenerated) {
        lines.push('**Auto-generated:** true  ');
    }
    lines.push('');
    lines.push('## Context');
    lines.push('');
    lines.push(d.context);
    lines.push('');
    lines.push('## Decision');
    lines.push('');
    lines.push(d.decision);
    lines.push('');
    lines.push('## Consequences');
    lines.push('');
    for (const c of d.consequences) {
        lines.push(`- ${c}`);
    }
    if (d.supersededBy) {
        lines.push('');
        lines.push(`> Superseded by ADR ${d.supersededBy}`);
    }
    lines.push('');
    return lines.join('\n');
}
function parseAdrMarkdown(content, id) {
    try {
        const titleMatch = content.match(/^# ADR \w+: (.+)$/m);
        const statusMatch = content.match(/\*\*Status:\*\* (.+?)(?:  |$)/m);
        const dateMatch = content.match(/\*\*Date:\*\* (.+?)(?:  |$)/m);
        const contextMatch = content.match(/## Context\n\n([\s\S]*?)\n\n## Decision/);
        const decisionMatch = content.match(/## Decision\n\n([\s\S]*?)\n\n## Consequences/);
        const consequencesMatch = content.match(/## Consequences\n\n([\s\S]*?)(?:\n\n> Superseded|$)/);
        const supersededMatch = content.match(/> Superseded by ADR (\w+)/);
        const autoMatch = content.match(/\*\*Auto-generated:\*\* true/);
        if (!titleMatch || !statusMatch || !dateMatch || !contextMatch || !decisionMatch || !consequencesMatch)
            return null;
        const consequences = consequencesMatch[1].split('\n').map(l => l.replace(/^- /, '').trim()).filter(Boolean);
        return {
            id,
            title: titleMatch[1].trim(),
            status: statusMatch[1].trim(),
            date: dateMatch[1].trim(),
            context: contextMatch[1].trim(),
            decision: decisionMatch[1].trim(),
            consequences,
            supersededBy: supersededMatch ? supersededMatch[1] : undefined,
            autoGenerated: autoMatch !== null,
        };
    }
    catch (err) {
        log.error('Failed to parse ADR markdown', { id, error: String(err) });
        return null;
    }
}
class AutoAdr {
    config;
    bus;
    constructor(config, bus) {
        this.config = {
            adrDir: config.adrDir ?? path_1.default.join(process.cwd(), 'docs', 'adr'),
            autoApproveThreshold: config.autoApproveThreshold ?? 3,
        };
        this.bus = bus;
        fs_1.default.mkdirSync(this.config.adrDir, { recursive: true });
    }
    async generate(decision) {
        const nextId = await this.nextId();
        const full = {
            ...decision,
            id: padId(nextId),
            date: new Date().toISOString().split('T')[0],
        };
        const filePath = path_1.default.join(this.config.adrDir, adrFilename(full.id, full.title));
        const content = renderAdrMarkdown(full);
        await promises_1.default.writeFile(filePath, content, 'utf-8');
        log.info(`ADR ${full.id} generated`, { file: filePath });
        await this.bus.publish('auto-adr.generated', { adr: full, filePath });
        return full;
    }
    async list() {
        const entries = await promises_1.default.readdir(this.config.adrDir);
        const results = [];
        for (const entry of entries) {
            if (!entry.startsWith('ADR-') || !entry.endsWith('.md'))
                continue;
            const idMatch = entry.match(/^ADR-(\w+)-/);
            if (!idMatch)
                continue;
            const content = await promises_1.default.readFile(path_1.default.join(this.config.adrDir, entry), 'utf-8');
            const parsed = parseAdrMarkdown(content, idMatch[1]);
            if (parsed)
                results.push(parsed);
        }
        return results.sort((a, b) => parseInt(a.id) - parseInt(b.id));
    }
    async get(id) {
        const entries = await promises_1.default.readdir(this.config.adrDir);
        for (const entry of entries) {
            if (entry.startsWith(`ADR-${id}-`) && entry.endsWith('.md')) {
                const content = await promises_1.default.readFile(path_1.default.join(this.config.adrDir, entry), 'utf-8');
                return parseAdrMarkdown(content, id);
            }
        }
        return null;
    }
    async supersede(id, newId) {
        const existing = await this.get(id);
        if (!existing)
            return null;
        const newAdr = await this.get(newId);
        if (!newAdr)
            return null;
        existing.status = 'superseded';
        existing.supersededBy = newId;
        const filePath = path_1.default.join(this.config.adrDir, adrFilename(existing.id, existing.title));
        await promises_1.default.writeFile(filePath, renderAdrMarkdown(existing), 'utf-8');
        await this.bus.publish('auto-adr.superseded', { oldId: id, newId });
        return existing;
    }
    async nextId() {
        const existing = await this.list();
        if (existing.length === 0)
            return 1;
        const maxId = Math.max(...existing.map(a => parseInt(a.id)));
        return maxId + 1;
    }
}
exports.AutoAdr = AutoAdr;
function createAutoAdr(bus, config) {
    return new AutoAdr(config, bus);
}
//# sourceMappingURL=auto-adr.js.map