export type AdrStatus = 'proposed' | 'accepted' | 'deprecated' | 'superseded';

export interface AdrDecision {
  id: string;
  title: string;
  status: AdrStatus;
  date: string;
  context: string;
  decision: string;
  consequences: string[];
  supersededBy?: string;
  autoGenerated?: boolean;
}

export interface AutoAdrConfig {
  adrDir: string;
  autoApproveThreshold: number;
}
