import { FeatureDefinition } from './types';

export function builtInFeatures(): FeatureDefinition[] {
  return [
    { id: 'project-scaffold', name: 'Project Scaffold', description: 'Create new projects from templates', category: 'scaffolding', visibility: 'available', minLevel: 'beginner', unlockConditions: [{ type: 'level', value: 'beginner' }], dependsOn: [], hints: ['Try "ideia init" to create your first project', 'Explore available templates with "ideia template list"'], commandHint: 'ideia init --help', group: 'getting-started' },
    { id: 'cli-help', name: 'CLI Help System', description: 'Access built-in help and documentation', category: 'core', visibility: 'available', minLevel: 'beginner', unlockConditions: [{ type: 'level', value: 'beginner' }], dependsOn: [], hints: ['Use ideia --help to see all commands', 'Try "ideia help <command>" for specific help'], commandHint: 'ideia --help', group: 'getting-started' },
    { id: 'basic-agent', name: 'Basic Agent', description: 'Run the AI agent for simple tasks', category: 'agent', visibility: 'available', minLevel: 'beginner', unlockConditions: [{ type: 'level', value: 'beginner' }], dependsOn: [], hints: ['Use "ideia run" to start a session', 'Try asking "create a new file"'], commandHint: 'ideia run "implement feature"', group: 'core-features' },
    { id: 'file-operations', name: 'File Operations', description: 'Create, read, update, and delete files', category: 'core', visibility: 'available', minLevel: 'beginner', unlockConditions: [{ type: 'level', value: 'beginner' }], dependsOn: [], hints: ['Agent can create and modify files', 'Use the explorer to navigate your project'], commandHint: 'Create a new file', group: 'core-features' },
    { id: 'code-generation', name: 'Code Generation', description: 'Generate code from natural language', category: 'agent', visibility: 'default', minLevel: 'beginner', unlockConditions: [{ type: 'level', value: 'beginner' }], dependsOn: ['basic-agent'], hints: ['Describe what you want to build', 'The agent will generate the code'], commandHint: 'Create a REST API endpoint', group: 'core-features' },
    { id: 'testing', name: 'Testing', description: 'Run and manage tests', category: 'quality', visibility: 'default', minLevel: 'intermediate', unlockConditions: [{ type: 'level', value: 'intermediate' }], dependsOn: ['file-operations'], hints: ['Tests are in __tests__/ directories', 'Use "ideia test" to run test suites'], commandHint: 'ideia test', group: 'quality' },
    { id: 'debugging', name: 'Debugging', description: 'Debug code with breakpoints and inspection', category: 'advanced', visibility: 'hidden', minLevel: 'intermediate', unlockConditions: [{ type: 'tutorial_completed', value: 'testing-tutorial' }], dependsOn: ['testing'], hints: ['Set breakpoints by clicking line numbers'], group: 'advanced-features' },
    { id: 'multi-agent', name: 'Multi-Agent Collaboration', description: 'Use specialized agents for complex tasks', category: 'agent', visibility: 'hidden', minLevel: 'advanced', unlockConditions: [{ type: 'level', value: 'advanced' }], dependsOn: ['basic-agent', 'code-generation'], hints: ['Use different agents for different tasks', 'Agents can work in parallel'], group: 'advanced-features' },
    { id: 'custom-agent', name: 'Custom Agent Creation', description: 'Create and configure custom agents', category: 'agent', visibility: 'hidden', minLevel: 'advanced', unlockConditions: [{ type: 'level', value: 'advanced' }, { type: 'feature_used', value: 'multi-agent' }], dependsOn: ['multi-agent'], hints: ['Define agents in JSON config'], group: 'advanced-features' },
    { id: 'workflow-automation', name: 'Workflow Automation', description: 'Create automated workflows and pipelines', category: 'automation', visibility: 'hidden', minLevel: 'expert', unlockConditions: [{ type: 'level', value: 'expert' }], dependsOn: ['custom-agent'], hints: ['Use workflow files to define pipelines'], group: 'advanced-features' },
    { id: 'security-scan', name: 'Security Scanning', description: 'Scan code for vulnerabilities', category: 'security', visibility: 'default', minLevel: 'intermediate', unlockConditions: [{ type: 'level', value: 'intermediate' }], dependsOn: [], hints: ['Regular security scans are recommended', 'Check the security dashboard'], commandHint: 'ideia scan security', group: 'quality' },
    { id: 'compliance', name: 'Compliance Checking', description: 'Check code against compliance rules', category: 'security', visibility: 'hidden', minLevel: 'intermediate', unlockConditions: [{ type: 'tutorial_completed', value: 'security-tutorial' }], dependsOn: ['security-scan'], hints: ['Run compliance checks before deployment'], commandHint: 'ideia compliance check', group: 'quality' },
    { id: 'performance', name: 'Performance Analysis', description: 'Analyze and optimize performance', category: 'analysis', visibility: 'hidden', minLevel: 'advanced', unlockConditions: [{ type: 'command_run', value: 'ideia test' }], dependsOn: [], hints: ['Use the performance dashboard'], group: 'analysis' },
    { id: 'coverage', name: 'Code Coverage', description: 'Track and improve test coverage', category: 'quality', visibility: 'default', minLevel: 'intermediate', unlockConditions: [{ type: 'level', value: 'intermediate' }], dependsOn: ['testing'], hints: ['Aim for at least 80% coverage'], commandHint: 'ideia coverage', group: 'quality' },
    { id: 'docs-gen', name: 'Documentation Generation', description: 'Generate documentation from code', category: 'docs', visibility: 'hidden', minLevel: 'intermediate', unlockConditions: [{ type: 'projects_created', value: 3 }], dependsOn: [], hints: ['Good docs improve team productivity'], commandHint: 'ideia docs generate', group: 'documentation' },
    { id: 'deployment', name: 'Deployment', description: 'Deploy applications to production', category: 'devops', visibility: 'hidden', minLevel: 'expert', unlockConditions: [{ type: 'level', value: 'expert' }, { type: 'projects_created', value: 5 }], dependsOn: ['workflow-automation'], hints: ['Set up CI/CD pipelines for automated deployment'], group: 'deployment' },
    { id: 'mcp-tools', name: 'MCP Tools', description: 'Use MCP servers for extended capabilities', category: 'extensions', visibility: 'hidden', minLevel: 'advanced', unlockConditions: [{ type: 'level', value: 'advanced' }], dependsOn: [], hints: ['Configure MCP servers in opencode.json'], group: 'extensions' },
    { id: 'self-optimization', name: 'Self-Optimization', description: 'Autonomous system optimization', category: 'advanced', visibility: 'hidden', minLevel: 'expert', unlockConditions: [{ type: 'badge_earned', value: 'power-user' }], dependsOn: ['workflow-automation'], hints: ['Let the system optimize itself automatically'], group: 'advanced-features' },
    { id: 'collaboration', name: 'Collaboration', description: 'Real-time collaboration features', category: 'advanced', visibility: 'hidden', minLevel: 'expert', unlockConditions: [{ type: 'time_spent_minutes', value: 10080 }], dependsOn: [], hints: ['Invite team members to collaborate'], group: 'collaboration' },
  ];
}
