import type { ContractDefinition, GeneratedContract } from './types';
import { createLogger } from '@ideia/logger';
import { TemplateEngine } from './template-engine';
const logger = createLogger('contract-generator');

export class ContractGenerator {
  private engine: TemplateEngine;

  constructor() {
    this.engine = new TemplateEngine();
  }

  async generate(
    modules: ContractDefinition[],
    format: 'zod' | 'valibot' | 'typescript' = 'zod',
    options?: { generateTests?: boolean; generateOpenAPI?: boolean },
  ): Promise<GeneratedContract[]> {
    const contracts: GeneratedContract[] = [];

    for (const mod of modules) {
      const schema = this.generateSchema(mod, format);
      contracts.push(schema);

      const iface = this.generateInterface(mod);
      contracts.push(iface);

      if (mod.events && mod.events.length > 0) {
        const events = this.generateEvents(mod);
        contracts.push(events);
      }

      if (options?.generateTests) {
        const test = this.generateContractTest(mod);
        contracts.push(test);
      }

      const registry = this.generateRegistryEntry(mod);
      contracts.push(registry);
    }

    if (options?.generateOpenAPI && modules.length > 0) {
      const spec = this.generateOpenAPISpec(modules);
      contracts.push(spec);
    }

    return contracts;
  }

  private generateSchema(mod: ContractDefinition, format: string): GeneratedContract {
    const moduleName = this.toPascalCase(mod.name);
    const ext = format === 'valibot' ? 'valibot' : 'zod';

    const importStmt = format === 'valibot'
      ? `import { object, string, number, array, optional, pipe, minLength, maxLength, email, enum as vEnum, InferOutput } from 'valibot';`
      : `import { z } from 'zod';`;

    let schemas = '';
    if (mod.interfaces) {
      schemas = mod.interfaces.flatMap(iface =>
        iface.methods.map(method => {
          const schemaName = `${this.toPascalCase(method.name)}Dto`;
          return this.generateDtoSchema(schemaName, method.params, format);
        }),
      ).join('\n\n');
    }

    const eventTypes = mod.events
      ? mod.events.map(e => {
          const eventName = `${this.toPascalCase(e.name)}Event`;
          return `export const ${eventName}Schema = z.object({\n  type: z.literal('${e.name}'),\n  payload: z.unknown(),\n  timestamp: z.string().datetime(),\n});\n\nexport type ${eventName} = z.infer<typeof ${eventName}Schema>;`;
        }).join('\n\n')
      : '';

    const content = `${importStmt}

// ${mod.name} module — Contracts
// Auto-generated by IDEIA Blueprint Generator

${schemas}

${eventTypes}

export interface I${moduleName}Contract {
${mod.interfaces ? mod.interfaces.map(iface => {
  const methods = iface.methods.map(m =>
    `  ${m.name}: (${m.params.map(p => `${p.name}: ${p.type}`).join(', ')}) => ${m.returns};`
  ).join('\n');
  return `  ${iface.name}: {\n${methods}\n  };`;
}).join('\n') : ''}
}
`;

    return {
      path: `src/modules/${mod.name}/contract/${mod.name}.contract.${ext}.ts`,
      content,
      format,
    };
  }

  private generateInterface(mod: ContractDefinition): GeneratedContract {
    const moduleName = this.toPascalCase(mod.name);

    let content = `// ${mod.name} module — Interface Definitions
// Auto-generated by IDEIA Blueprint Generator

`;

    if (mod.interfaces) {
      for (const iface of mod.interfaces) {
        content += `export interface ${iface.name} {\n`;
        for (const method of iface.methods) {
          const params = method.params.map(p => `${p.name}: ${p.type}`).join(', ');
          content += `  ${method.name}(${params}): ${method.returns};\n`;
        }
        content += `}\n\n`;
      }
    }

    if (mod.events) {
      for (const event of mod.events) {
        content += `export interface ${this.toPascalCase(event.name)}EventPayload {\n`;
        content += `  ${event.payload}\n`;
        content += `}\n\n`;
      }

      content += `export type ${moduleName}Events = {\n`;
      for (const event of mod.events) {
        content += `  '${event.name}': ${this.toPascalCase(event.name)}EventPayload;\n`;
      }
      content += `};\n`;
    }

    return {
      path: `src/modules/${mod.name}/contract/${mod.name}.interfaces.ts`,
      content,
      format: 'typescript',
    };
  }

  private generateEvents(mod: ContractDefinition): GeneratedContract {
    const moduleName = this.toPascalCase(mod.name);
    const events = mod.events || [];

    const content = `// ${mod.name} module — Event Types
// Auto-generated by IDEIA Blueprint Generator

export const ${moduleName}EventTypes = {
${events.map(e => `  ${this.toCamelCase(e.name)}: '${mod.name}.${e.name}'`).join(',\n')}
} as const;

export type ${moduleName}EventType = (typeof ${moduleName}EventTypes)[keyof typeof ${moduleName}EventTypes];

${events.map(e => {
  const payloadName = `${this.toPascalCase(e.name)}Payload`;
  return `export interface ${payloadName} {\n  ${e.payload}\n}`;
}).join('\n\n')}

export type ${moduleName}EventPayloads = {
${events.map(e => `  [${moduleName}EventTypes.${this.toCamelCase(e.name)}]: ${this.toPascalCase(e.name)}Payload`).join(';\n')}
};
`;

    return {
      path: `src/modules/${mod.name}/contract/${mod.name}.events.ts`,
      content,
      format: 'typescript',
    };
  }

  private generateContractTest(mod: ContractDefinition): GeneratedContract {
    const moduleName = this.toPascalCase(mod.name);

    const content = `import { describe, it, expect } from '@jest/globals';
import { z } from 'zod';
import type { I${moduleName}Contract } from './${mod.name}.contract.zod';

// ${mod.name} — Contract Tests
// Auto-generated by IDEIA Blueprint Generator

describe('${mod.name} Module Contract', () => {
${mod.interfaces ? mod.interfaces.map(iface =>
  iface.methods.map(m => {
    const _params = m.params.map(p => `${p.name}: ${p.type}`).join(', ');
    return `  it('${iface.name}.${m.name} should have correct signature', () => {
    // Type-level test: verifies the contract signature is valid
    const stub: Pick<I${moduleName}Contract['${iface.name}'], '${m.name}'> = {
      ${m.name}: (${m.params.map(p => p.name).join(', ')}) => {
        return Promise.resolve({} as ${m.returns.replace('Promise<', '').replace('>', '')});
      },
    };
    expect(stub.${m.name}).toBeDefined();
  });`;
  }).join('\n\n')
).join('\n\n') : ''}
});
`;

    return {
      path: `src/modules/${mod.name}/contract/__tests__/${mod.name}.contract.test.ts`,
      content,
      format: 'typescript',
    };
  }

  private generateRegistryEntry(mod: ContractDefinition): GeneratedContract {
    const moduleName = this.toPascalCase(mod.name);

    const content = `// ${mod.name} — Contract Registry Entry
// Auto-generated by IDEIA Blueprint Generator

import type { I${moduleName}Contract } from './${mod.name}.contract.zod';
import type { ${moduleName}Events } from './${mod.name}.events';

export const ${mod.name}ContractRegistry = {
  name: '${mod.name}',
  version: '${mod.version || '0.1.0'}',
  description: '${mod.description || `${mod.name} module contracts`}',
  schemaFormat: 'zod' as const,
  interfaces: ['${(mod.interfaces || []).map(i => i.name).join("', '")}'],
  events: ['${(mod.events || []).map(e => e.name).join("', '")}'],
};

export type { I${moduleName}Contract };
export type { ${moduleName}Events };
`;

    return {
      path: `src/modules/${mod.name}/contract/index.ts`,
      content,
      format: 'typescript',
    };
  }

  private generateOpenAPISpec(modules: ContractDefinition[]): GeneratedContract {
    const paths: Record<string, unknown> = {};

    for (const mod of modules) {
      if (mod.interfaces) {
        for (const iface of mod.interfaces) {
          for (const method of iface.methods) {
            if (method.name.startsWith('find') || method.name.startsWith('get') ||
                method.name.startsWith('create') || method.name.startsWith('update') ||
                method.name.startsWith('delete')) {
              const basePath = `/api/${mod.name}s`;
              const operation = method.name.startsWith('findAll') ? 'get' :
                method.name.startsWith('findById') || method.name.startsWith('getById') ? 'get' :
                method.name.startsWith('create') ? 'post' :
                method.name.startsWith('update') ? 'put' :
                method.name.startsWith('delete') ? 'delete' : 'post';

              const pathKey = operation === 'get' && (method.name.includes('ById') || method.name.includes('findById'))
                ? `${basePath}/{id}`
                : basePath;

              if (!paths[pathKey]) {
                paths[pathKey] = {};
              }
              (paths[pathKey] as Record<string, unknown>)[operation] = {
                summary: `${this.toPascalCase(method.name)} ${mod.name}`,
                operationId: `${mod.name}.${method.name}`,
                parameters: method.params.map(p => ({
                  name: p.name,
                  in: p.name === 'id' ? 'path' : 'query',
                  required: p.name === 'id',
                  schema: { type: this.mapTypeToOpenAPI(p.type) },
                })),
                responses: {
                  '200': {
                    description: 'Success',
                    content: {
                      'application/json': {
                        schema: {
                          type: 'object',
                        },
                      },
                    },
                  },
                },
              };
            }
          }
        }
      }
    }

    const spec: Record<string, unknown> = {
      openapi: '3.0.3',
      info: {
        title: `${this.toPascalCase(modules[0]?.name || 'API')} Service`,
        version: '1.0.0',
        description: 'Auto-generated API specification',
      },
      paths,
    };

    return {
      path: 'docs/api/openapi.json',
      content: JSON.stringify(spec, null, 2),
      format: 'openapi',
    };
  }

  private generateDtoSchema(name: string, params: { name: string; type: string }[], format: string): string {
    const fields = params.map(p => {
      const fieldName = p.name;
      const zodType = this.mapTypeToZod(p.type);
      return `  ${fieldName}: ${zodType},`;
    }).join('\n');

    if (format === 'valibot') {
      return `const ${name}Schema = object({\n${fields}\n});\n\nexport type ${name} = InferOutput<typeof ${name}Schema>;`;
    }

    return `export const ${name}Schema = z.object({\n${fields}\n});\n\nexport type ${name} = z.infer<typeof ${name}Schema>;`;
  }

  private mapTypeToZod(type: string): string {
    const t = type.toLowerCase();
    if (t.includes('string')) return 'z.string()';
    if (t.includes('number')) return 'z.number()';
    if (t.includes('boolean')) return 'z.boolean()';
    if (t.includes('date')) return 'z.string().datetime()';
    if (t.includes('uuid')) return 'z.string().uuid()';
    if (t.includes('email')) return 'z.string().email()';
    return 'z.unknown()';
  }

  private mapTypeToOpenAPI(type: string): string {
    const t = type.toLowerCase();
    if (t.includes('string') || t.includes('uuid') || t.includes('email') || t.includes('date')) return 'string';
    if (t.includes('number')) return 'number';
    if (t.includes('boolean')) return 'boolean';
    return 'string';
  }

  private toPascalCase(str: string): string {
    return str.replace(/([-_\s]+(.)|^\w)/g, (_, __, c) => c ? c.toUpperCase() : _.toUpperCase());
  }

  private toCamelCase(str: string): string {
    return str.replace(/([-_\s]+(.)|^\w)/g, (match, _, c) =>
      match.indexOf('-') > -1 || match.indexOf('_') > -1 || match.indexOf(' ') > -1
        ? (c ? c.toUpperCase() : '')
        : match.toLowerCase(),
    );
  }
}
