/**
 * generate-all-workflows.ts — Gera/atualiza todos os workflows GitHub Actions
 *
 * Uso:
 *   npx tsx scripts/generate-all-workflows.ts          # gera todos
 *   npx tsx scripts/generate-all-workflows.ts --dry-run # mostra o que seria gerado
 *   npx tsx scripts/generate-all-workflows.ts --env production  # apenas um ambiente
 */

import { generateGitHubActionsWorkflow, GitHubPipelineConfig } from '../packages/delivery-orchestrator/src/gitops-generator';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');
const WORKFLOWS_DIR = join(ROOT, '.github', 'workflows');

interface EnvConfig {
  name: string;
  environment: string;
  branch: string;
  qualityGates: string[];
  deployOnPush: boolean;
}

const ENVIRONMENTS: EnvConfig[] = [
  {
    name: 'IDEIA CI — Development',
    environment: 'development',
    branch: 'develop',
    qualityGates: ['lint', 'test', 'build'],
    deployOnPush: false,
  },
  {
    name: 'IDEIA CI — Staging',
    environment: 'staging',
    branch: 'main',
    qualityGates: ['lint', 'test', 'build', 'security'],
    deployOnPush: true,
  },
  {
    name: 'IDEIA CD — Production',
    environment: 'production',
    branch: 'main',
    qualityGates: ['lint', 'test', 'build', 'security', 'architecture'],
    deployOnPush: false,
  },
];

function getExistingWorkflows(): Set<string> {
  if (!existsSync(WORKFLOWS_DIR)) return new Set();
  const { readdirSync } = require('node:fs');
  return new Set(readdirSync(WORKFLOWS_DIR).filter((f: string) => f.endsWith('.yml')));
}

function generateReleaseAutoWorkflow(): string {
  return `# Auto-generated by IDEIA generate-all-workflows
name: Release Auto

on:
  push:
    tags:
      - 'v*'

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: npx eslint . --max-warnings=0
      - name: Test
        run: npx jest --passWithNoTests
      - name: Build
        run: npx tsc --noEmit
      - name: Security
        run: npm audit --audit-level=high

  release-notes:
    needs: quality-gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: |
          echo "## Release \${GITHUB_REF_NAME}" > RELEASE_NOTES.md
          git log --oneline --format="* %s" \$(git describe --tags --abbrev=0 HEAD^)..HEAD >> RELEASE_NOTES.md || true
      - uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: RELEASE_NOTES.md

  deploy-staging:
    needs: release-notes
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying \${GITHUB_REF_NAME} to staging"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying \${GITHUB_REF_NAME} to production"
`;
}

function generateReviewGateWorkflow(): string {
  return `# Auto-generated by IDEIA generate-all-workflows
name: Review Gate

on:
  workflow_dispatch:
    inputs:
      deployId:
        description: 'Deploy ID to review'
        required: true
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

jobs:
  review:
    runs-on: ubuntu-latest
    environment: \${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Review Gate for \${{ github.event.inputs.deployId }}
        run: |
          echo "Review required for deploy \${{ github.event.inputs.deployId }}"
          echo "Environment: \${{ github.event.inputs.environment }}"
      - name: Notify
        run: |
          echo "Review notification sent for \${{ github.event.inputs.deployId }}"
`;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const targetEnv = args.includes('--env') ? args[args.indexOf('--env') + 1] : null;

  const envs = targetEnv
    ? ENVIRONMENTS.filter(e => e.environment === targetEnv)
    : ENVIRONMENTS;

  if (envs.length === 0) {
    console.error(`Unknown environment: ${targetEnv}`);
    process.exit(1);
  }

  if (!existsSync(WORKFLOWS_DIR)) {
    if (!dryRun) mkdirSync(WORKFLOWS_DIR, { recursive: true });
    console.log(`Created ${WORKFLOWS_DIR}`);
  }

  const existing = getExistingWorkflows();
  const generated: string[] = [];
  const skipped: string[] = [];

  for (const env of envs) {
    const config: GitHubPipelineConfig = {
      name: env.name,
      version: '1.0.0',
      environment: env.environment,
      branches: [env.branch],
      deployOnPush: env.deployOnPush,
      qualityGates: env.qualityGates,
    };

    const filename = `deploy-${env.environment}.yml`;

    if (existing.has(filename)) {
      skipped.push(filename);
      console.log(`  ⏩ ${filename} already exists (use --force to overwrite)`);
      continue;
    }

    if (!dryRun) {
      const filePath = generateGitHubActionsWorkflow(config, ROOT);
      generated.push(filename);
      console.log(`  ✅ ${filename} generated at ${filePath}`);
    } else {
      generated.push(filename);
      console.log(`  📋 ${filename} (dry-run)`);
    }
  }

  const extraFiles: Array<{ name: string; content: string; desc: string }> = [
    { name: 'release-auto.yml', content: generateReleaseAutoWorkflow(), desc: 'Release Auto workflow' },
    { name: 'review-gate.yml', content: generateReviewGateWorkflow(), desc: 'Review Gate workflow' },
  ];

  for (const file of extraFiles) {
    const filePath = join(WORKFLOWS_DIR, file.name);
    if (existing.has(file.name)) {
      skipped.push(file.name);
      console.log(`  ⏩ ${file.name} already exists`);
      continue;
    }
    if (!dryRun) {
      writeFileSync(filePath, file.content, 'utf-8');
      generated.push(file.name);
      console.log(`  ✅ ${file.name} generated`);
    } else {
      generated.push(file.name);
      console.log(`  📋 ${file.name} (dry-run)`);
    }
  }

  console.log(`\nSummary: ${generated.length} generated, ${skipped.length} skipped`);
}

main().catch(err => {
  console.error('Failed:', err);
  process.exit(1);
});
