import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export interface GitHubPipelineConfig {
  name: string;
  version: string;
  environment: string;
  branches?: string[];
  deployOnPush?: boolean;
  qualityGates?: string[];
}

export function generateGitHubActionsWorkflow(config: GitHubPipelineConfig, cwd: string): string {
  const workflowsDir = join(cwd, '.github', 'workflows');
  if (!existsSync(workflowsDir)) {
    mkdirSync(workflowsDir, { recursive: true });
  }

  const gates = config.qualityGates || ['lint', 'test', 'build', 'security', 'architecture'];
  const gateSteps = gates.map(gate => {
    const cmds: Record<string, string> = {
      lint: 'npx eslint . --max-warnings=0',
      test: 'npx jest --passWithNoTests',
      build: 'npx tsc --noEmit',
      security: 'npm audit --audit-level=high',
      architecture: 'npx tsc -b --dry',
    };
    return `      - name: ${gate}
        run: ${cmds[gate] || `echo "Gate: ${gate}"`}`;
  }).join('\n');

  const workflowYaml = `# Auto-generated by IDEIA DeliveryOrchestrator
name: ${config.name}

on:
  push:
    branches: [${(config.branches || ['main']).map(b => `"${b}"`).join(', ')}]
  pull_request:
    branches: [${(config.branches || ['main']).map(b => `"${b}"`).join(', ')}]

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
${gateSteps}

  deploy:
    needs: quality-gates
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${config.environment}
    env:
      VERSION: "${config.version}"
      ENVIRONMENT: "${config.environment}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy v\${VERSION} to \${ENVIRONMENT}
        run: |
          echo "Deploying v\${VERSION} to \${ENVIRONMENT}"
          mkdir -p .deploy/current
          cp -r dist/* .deploy/current/ || true
          echo "\${VERSION}" > .deploy/active-version.txt
      - name: Health Check
        run: |
          echo "Running health check..."
          sleep 5
          echo "Deploy complete"
`;

  const filePath = join(workflowsDir, `deploy-${config.environment}.yml`);
  writeFileSync(filePath, workflowYaml, 'utf-8');
  return filePath;
}

export interface GitOpsStatus {
  enabled: boolean;
  provider: 'github-actions' | 'argo-cd' | 'manual';
  workflowPath?: string;
  lastSyncAt?: string;
  currentVersion?: string;
}

export function createGitOpsConfig(environment: string, cwd: string, pipelineConfig?: GitHubPipelineConfig): GitOpsStatus {
  const workflowsDir = join(cwd, '.github', 'workflows');
  const workflowPath = join(workflowsDir, `deploy-${environment}.yml`);

  if (!existsSync(workflowPath) && pipelineConfig) {
    const generatedPath = generateGitHubActionsWorkflow(
      { name: pipelineConfig.name, version: pipelineConfig.version, environment, branches: pipelineConfig.branches, deployOnPush: pipelineConfig.deployOnPush, qualityGates: pipelineConfig.qualityGates },
      cwd,
    );
    return {
      enabled: true,
      provider: 'github-actions',
      workflowPath: generatedPath,
    };
  }

  return {
    enabled: existsSync(workflowPath),
    provider: existsSync(workflowPath) ? 'github-actions' : 'manual',
    workflowPath: existsSync(workflowPath) ? workflowPath : undefined,
  };
}
