import { describe, it, expect, jest } from '@jest/globals';
import { AutoAdrIntegration, createAutoAdrIntegration } from '../src/auto-adr-integration';
import { AutoAdr } from '../src/auto-adr';
import { EventBus } from '@ideia/event-bus';
import type { AutoFixEvent } from '../src/auto-adr-integration';

class MockEventBus {
  private handlers = new Map<string, Array<(event: unknown) => void>>();
  private idCounter = 0;

  async subscribe(eventType: string, handler: (event: unknown) => void): Promise<string> {
    const id = `sub-${++this.idCounter}`;
    if (!this.handlers.has(eventType)) {
      this.handlers.set(eventType, []);
    }
    this.handlers.get(eventType)!.push(handler);
    return id;
  }

  async unsubscribe(_id: string): Promise<boolean> {
    return true;
  }

  emit(event: any): Promise<unknown> {
    const handlers = this.handlers.get(event.type) || [];
    for (const h of handlers) {
      h(event);
    }
    return Promise.resolve(event);
  }

  trigger(eventType: string, payload: unknown): void {
    const handlers = this.handlers.get(eventType) || [];
    for (const h of handlers) {
      h({ type: eventType, payload, source: 'test' });
    }
  }
}

describe('AutoAdrIntegration', () => {
  it('should create via factory', () => {
    const bus = new MockEventBus() as unknown as EventBus;
    const autoAdr = new AutoAdr({}, bus);
    const integration = createAutoAdrIntegration(autoAdr, bus);
    expect(integration).toBeInstanceOf(AutoAdrIntegration);
  });

  it('should generate ADR from fix event', async () => {
    const bus = new MockEventBus() as unknown as EventBus;
    const autoAdr = new AutoAdr({ adrDir: require('os').tmpdir() }, bus);
    const integration = new AutoAdrIntegration(autoAdr, bus);

    const fix: AutoFixEvent = {
      fixId: 'fix-001',
      filePath: 'src/core/validator.ts',
      description: 'Fix null pointer in input validation',
      changeType: 'bugfix',
      appliedAt: new Date().toISOString(),
      appliedBy: 'auto-fix',
    };

    const adrId = await integration.generateAdrFromFix(fix);
    expect(adrId).toBeDefined();

    const adr = await autoAdr.get(adrId);
    expect(adr).not.toBeNull();
    expect(adr!.title).toContain('Fix null pointer');
    expect(adr!.status).toBe('accepted');
    expect(adr!.autoGenerated).toBe(true);
  });

  it('should generate ADR from self-fix', async () => {
    const bus = new MockEventBus() as unknown as EventBus;
    const autoAdr = new AutoAdr({ adrDir: require('os').tmpdir() }, bus);
    const integration = new AutoAdrIntegration(autoAdr, bus);

    const adrId = await integration.generateAdrFromSelfFix('opt-123', 'src/optimizer.ts', 'Optimize loop performance');
    expect(adrId).toBeDefined();
    const adr = await autoAdr.get(adrId);
    expect(adr).not.toBeNull();
    expect(adr!.title).toContain('Optimize loop');
  });

  it('should listen for self.fix.applied events', async () => {
    const mockBus = new MockEventBus();
    const bus = mockBus as unknown as EventBus;
    const autoAdr = new AutoAdr({ adrDir: require('os').tmpdir() }, bus);
    const integration = new AutoAdrIntegration(autoAdr, bus);

    const generateSpy = jest.spyOn(integration, 'generateAdrFromFix');
    await integration.start();

    mockBus.trigger('self.fix.applied', {
      fixId: 'fix-002',
      filePath: 'src/auth.ts',
      description: 'Fix CSRF token validation',
      changeType: 'security',
    });

    await new Promise(r => setTimeout(r, 100));
    expect(generateSpy).toHaveBeenCalled();
    await integration.stop();
  });

  it('should add security consequence for security fixes', async () => {
    const bus = new MockEventBus() as unknown as EventBus;
    const autoAdr = new AutoAdr({ adrDir: require('os').tmpdir() }, bus);
    const integration = new AutoAdrIntegration(autoAdr, bus);

    const adrId = await integration.generateAdrFromFix({
      fixId: 'sec-001',
      filePath: 'src/crypto.ts',
      description: 'Patch timing attack vulnerability',
      changeType: 'security',
      appliedAt: new Date().toISOString(),
      appliedBy: 'auto-fix',
    });

    const adr = await autoAdr.get(adrId);
    expect(adr!.consequences.some(c => c.toLowerCase().includes('security'))).toBe(true);
  });

  it('should add refactoring consequence for refactors', async () => {
    const bus = new MockEventBus() as unknown as EventBus;
    const autoAdr = new AutoAdr({ adrDir: require('os').tmpdir() }, bus);
    const integration = new AutoAdrIntegration(autoAdr, bus);

    const adrId = await integration.generateAdrFromFix({
      fixId: 'ref-001',
      filePath: 'src/utils.ts',
      description: 'Extract helper functions',
      changeType: 'refactor',
      appliedAt: new Date().toISOString(),
      appliedBy: 'auto-fix',
    });

    const adr = await autoAdr.get(adrId);
    expect(adr!.consequences.some(c => c.toLowerCase().includes('refactor'))).toBe(true);
  });
});
