import path from 'path';
import fs from 'fs';
import os from 'os';
import { EventBus } from '@ideia/event-bus';

const busMock = { emit: async () => {}, publish: async () => {} } as unknown as EventBus;

async function createAutoAdrWithMock(tmpDir: string) {
  const mod = await import('../src/auto-adr');
  return new mod.AutoAdr({ adrDir: tmpDir }, busMock);
}

describe('AutoAdr C20 — Enhanced', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'auto-adr-test-'));
  });

  afterEach(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
  });

  it('should create instance with config', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    expect(adr).toBeDefined();
  });

  it('should generate an ADR', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    const result = await adr.generate({
      title: 'Test Decision',
      status: 'proposed',
      context: 'Testing ADR generation',
      decision: 'Use TypeScript throughout',
      consequences: ['Type safety', 'Better tooling'],
      autoGenerated: true,
    });
    expect(result.id).toBe('0001');
    expect(result.title).toContain('Test Decision');
    expect(result.status).toBe('proposed');
    expect(result.consequences).toHaveLength(2);
  });

  it('should list ADRs', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    await adr.generate({ title: 'First', status: 'proposed', context: 'First', decision: 'Yes', consequences: ['A'] });
    await adr.generate({ title: 'Second', status: 'accepted', context: 'Second', decision: 'Yes', consequences: ['B'] });
    const list = await adr.list();
    expect(list).toHaveLength(2);
    expect(list[0].title).toBe('First');
    expect(list[1].title).toBe('Second');
  });

  it('should get specific ADR by id', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    await adr.generate({ title: 'First', status: 'proposed', context: 'Ctx', decision: 'Dec', consequences: ['C1'] });
    const found = await adr.get('0001');
    expect(found).not.toBeNull();
    expect(found!.title).toBe('First');
  });

  it('should return null for non-existent ADR', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    const found = await adr.get('9999');
    expect(found).toBeNull();
  });

  it('should supersede an ADR', async () => {
    const adr = await createAutoAdrWithMock(tmpDir);
    await adr.generate({ title: 'Old', status: 'accepted', context: 'Old way', decision: 'Old', consequences: ['C1'] });
    await adr.generate({ title: 'New', status: 'accepted', context: 'New way', decision: 'New', consequences: ['C2'] });
    const superseded = await adr.supersede('0001', '0002');
    expect(superseded).not.toBeNull();
    expect(superseded!.status).toBe('superseded');
    expect(superseded!.supersededBy).toBe('0002');
  });

  it('should handle file-based persistence across instances', async () => {
    const adr1 = await createAutoAdrWithMock(tmpDir);
    await adr1.generate({ title: 'Persistent', status: 'proposed', context: 'Test', decision: 'Yes', consequences: ['C'] });
    const adr2 = await createAutoAdrWithMock(tmpDir);
    const list = await adr2.list();
    expect(list).toHaveLength(1);
    expect(list[0].title).toBe('Persistent');
  });

  it('should create via factory function', async () => {
    const mod = await import('../src/auto-adr');
    const adr = mod.createAutoAdr(busMock, { adrDir: tmpDir });
    expect(adr).toBeDefined();
  });

  it('should emit event on generate', async () => {
    const localBus = { emit: jest.fn().mockResolvedValue(undefined), publish: jest.fn().mockResolvedValue(undefined) };
    const mod = await import('../src/auto-adr');
    const adr = new mod.AutoAdr({ adrDir: tmpDir }, localBus as unknown as EventBus);
    await adr.generate({ title: 'Event Test', status: 'proposed', context: 'Test', decision: 'Yes', consequences: ['C'] });
    const called = localBus.emit.mock.calls.length > 0 || localBus.publish.mock.calls.length > 0;
    expect(called).toBe(true);
  });
});
