import { adapterCommand } from '../commands/adapter';
import { auditCommand } from '../commands/audit';
import { backupStatusCommand as backupCommand } from '../commands/backup';
import { ciCommand } from '../commands/ci';
import { complianceCommand } from '../commands/compliance';
import { contextCommand } from '../commands/context';
import { contractCommand } from '../commands/contract';
import { designCommand } from '../commands/design';
import { driftCommand } from '../commands/drift';
import { ecosystemCommand } from '../commands/ecosystem';
import { featureFlagCommand } from '../commands/feature-flag';
import { featureCommand } from '../commands/feature';
import { gateCommand } from '../commands/gate';
import { generateCommand } from '../commands/generate';
import { initCommand } from '../commands/init';
import { knowledgeCommand } from '../commands/knowledge';
import { learnCommand } from '../commands/learn';
import { mcpCommand } from '../commands/mcp';
import { observabilityCommand } from '../commands/observability';
import { performanceCommand } from '../commands/performance';
import { pluginCommand } from '../commands/plugin';
import { promptCommand } from '../commands/prompt';
import { proveCommand } from '../commands/prove';
import { ragCommand } from '../commands/rag';
import { releaseCommand } from '../commands/release';
import { reviewCommand } from '../commands/review';
import { rulesCommand } from '../commands/rules';
import { securityCommand } from '../commands/security';
import { snapshotCommand } from '../commands/snapshot';
import { streamCommand } from '../commands/stream';
import { supplyChainCommand } from '../commands/supply-chain';
import { syncCommand } from '../commands/sync';
import { timelineCommand } from '../commands/timeline';
import { verifyCommand } from '../commands/verify';
import { workflowCommand } from '../commands/workflow';
import { worktreeCommand } from '../commands/worktree';
import { prReviewCommand } from '../commands/pr-review';
import fs from 'node:fs';
import path from 'node:path';

describe('Deep Commands — all command modules export function', () => {
  it('adapterCommand deve ser função', () => { expect(typeof adapterCommand).toBe('function'); });
  it('auditCommand deve ser função', () => { expect(typeof auditCommand).toBe('function'); });
  it('backupCommand deve ser função', () => { expect(typeof backupCommand).toBe('function'); });
  it('ciCommand deve ser função', () => { expect(typeof ciCommand).toBe('function'); });
  it('complianceCommand deve ser função', () => { expect(typeof complianceCommand).toBe('function'); });
  it('contextCommand deve ser função', () => { expect(typeof contextCommand).toBe('function'); });
  it('contractCommand deve ser função', () => { expect(typeof contractCommand).toBe('function'); });
  it('designCommand deve ser função', () => { expect(typeof designCommand).toBe('function'); });
  it('driftCommand deve ser função', () => { expect(typeof driftCommand).toBe('function'); });
  it('ecosystemCommand deve ser função', () => { expect(typeof ecosystemCommand).toBe('function'); });
  it('featureFlagCommand deve ser função', () => { expect(typeof featureFlagCommand).toBe('function'); });
  it('featureCommand deve ser função', () => { expect(typeof featureCommand).toBe('function'); });
  it('gateCommand deve ser função', () => { expect(typeof gateCommand).toBe('function'); });
  it('generateCommand deve ser função', () => { expect(typeof generateCommand).toBe('function'); });
  it('initCommand deve ser função', () => { expect(typeof initCommand).toBe('function'); });
  it('knowledgeCommand deve ser função', () => { expect(typeof knowledgeCommand).toBe('function'); });
  it('learnCommand deve ser função', () => { expect(typeof learnCommand).toBe('function'); });
  it('mcpCommand deve ser função', () => { expect(typeof mcpCommand).toBe('function'); });
  it('observabilityCommand deve ser função', () => { expect(typeof observabilityCommand).toBe('function'); });
  it('performanceCommand deve ser função', () => { expect(typeof performanceCommand).toBe('function'); });
  it('pluginCommand deve ser função', () => { expect(typeof pluginCommand).toBe('function'); });
  it('promptCommand deve ser função', () => { expect(typeof promptCommand).toBe('function'); });
  it('proveCommand deve ser função', () => { expect(typeof proveCommand).toBe('function'); });
  it('ragCommand deve ser função', () => { expect(typeof ragCommand).toBe('function'); });
  it('releaseCommand deve ser função', () => { expect(typeof releaseCommand).toBe('function'); });
  it('reviewCommand deve ser função', () => { expect(typeof reviewCommand).toBe('function'); });
  it('rulesCommand deve ser função', () => { expect(typeof rulesCommand).toBe('function'); });
  it('all command files should export a function', () => {
    const cmdsDir = path.join(__dirname, '../commands');
    const files = fs.readdirSync(cmdsDir).filter(f => f.endsWith('.ts') || f.endsWith('.js'));
    expect(files.length).toBeGreaterThan(0);
  });
  it('securityCommand deve ser função', () => { expect(typeof securityCommand).toBe('function'); });
  it('snapshotCommand deve ser função', () => { expect(typeof snapshotCommand).toBe('function'); });
  it('streamCommand deve ser função', () => { expect(typeof streamCommand).toBe('function'); });
  it('supplyChainCommand deve ser função', () => { expect(typeof supplyChainCommand).toBe('function'); });
  it('syncCommand deve ser função', () => { expect(typeof syncCommand).toBe('function'); });
  it('timelineCommand deve ser função', () => { expect(typeof timelineCommand).toBe('function'); });
  it('verifyCommand deve ser função', () => { expect(typeof verifyCommand).toBe('function'); });
  it('workflowCommand deve ser função', () => { expect(typeof workflowCommand).toBe('function'); });
  it('worktreeCommand deve ser função', () => { expect(typeof worktreeCommand).toBe('function'); });
  it('prReviewCommand deve ser função', () => { expect(typeof prReviewCommand).toBe('function'); });
});
