import { EventBus } from '@ideia/event-bus';
import { TechnologyRadar } from '@ideia/technology-radar';
import { AutoAdr } from '@ideia/auto-adr';
import { createLogger } from '@ideia/logger';
import { ChatMessage } from './types';

const log = createLogger('self-chat');

export class SelfChat {
  private history: ChatMessage[] = [];

  constructor(
    private eventBus?: EventBus,
    private technologyRadar?: TechnologyRadar,
    private autoAdr?: AutoAdr,
  ) {}

  async processMessage(content: string): Promise<ChatMessage> {
    const userMsg: ChatMessage = {
      role: 'user',
      content,
      timestamp: new Date().toISOString(),
    };
    this.history.push(userMsg);

    let responseContent = '';

    const lower = content.toLowerCase();
    if (lower.includes('radar') || lower.includes('technology') || lower.includes('tech')) {
      const techName = content.replace(/radar|technology|tech|research|scan/gi, '').trim();
      if (techName && this.technologyRadar) {
        responseContent = await this.researchTopic(techName);
      } else {
        const recs = this.technologyRadar?.getRecommendations() ?? [];
        responseContent = recs.length > 0
          ? `Top recommendation: ${recs[0]?.technology.name} (score: ${recs[0]?.score?.toFixed(2)})`
          : 'No recommendations available. Run a radar scan first.';
      }
    } else if (lower.includes('feature') || lower.includes('implement') || lower.includes('adr')) {
      responseContent = await this.requestFeature(content);
    } else if (lower.includes('health') || lower.includes('status')) {
      responseContent = 'System health check: All systems nominal. Use `dashboard getHealth` for detailed metrics.';
    } else {
      responseContent = `I can help with IDEIA topics. Try asking about: technology radar, recommendations, feature implementation, ADR generation, or system health.`;
    }

    const assistantMsg: ChatMessage = {
      role: 'assistant',
      content: responseContent,
      timestamp: new Date().toISOString(),
    };
    this.history.push(assistantMsg);

    if (this.eventBus) {
      try {
        await this.eventBus.emit({
          type: 'self-chat.message',
          source: 'self-optimization-panel',
          payload: { userMessage: userMsg, response: assistantMsg },
        });
      } catch {
        /* background */
      }
    }

    return assistantMsg;
  }

  getHistory(): ChatMessage[] {
    return [...this.history];
  }

  async researchTopic(topic: string): Promise<string> {
    if (this.technologyRadar) {
      try {
        const results = await this.technologyRadar.scan();
        const match = results.find(
          t => t.name.toLowerCase().includes(topic.toLowerCase()),
        );
        if (match) {
          return `Research on "${topic}": Found ${match.name} — ${match.description}. Score: ${match.scores.weightedTotal.toFixed(2)}.`;
        }
      } catch (err) {
        log.error('Research failed', { topic, error: String(err) });
        return `Could not research "${topic}" at this time.`;
      }
    }
    return `Technology Radar not available. Cannot research "${topic}".`;
  }

  async requestFeature(description: string): Promise<string> {
    if (this.autoAdr) {
      try {
        const adr = await this.autoAdr.generate({
          title: `Feature: ${description.slice(0, 60)}`,
          status: 'proposed',
          context: `User requested feature: ${description}`,
          decision: 'Implement as part of self-optimization pipeline',
          consequences: [
            'Requires implementation effort',
            'Adds new capability to the system',
            'Should be documented and tested',
          ],
          autoGenerated: true,
        });
        return `Feature request captured as ADR ${adr.id}: ${adr.title}`;
      } catch (err) {
        log.error('Feature request failed', { description, error: String(err) });
        return `Could not create feature request: ${String(err)}`;
      }
    }
    return `Auto-ADR not available. Feature request noted: "${description}"`;
  }
}

export function createSelfChat(
  eventBus?: EventBus,
  technologyRadar?: TechnologyRadar,
  autoAdr?: AutoAdr,
): SelfChat {
  return new SelfChat(eventBus, technologyRadar, autoAdr);
}
