import type { ProfileType, AutonomyLevel, WizardSummary } from './types.js'
import { createLogger } from '@ideia/logger';
const logger = createLogger('config-generator');

export interface ConfigPreset {
  autonomyLevel: AutonomyLevel
  features: Record<string, boolean>
  security: Record<string, unknown>
}

const PROFILE_PRESETS: Record<ProfileType, ConfigPreset> = {
  'solo-dev': {
    autonomyLevel: 'N2',
    features: { autoScan: true, fileWatching: true, notifications: true },
    security: { level: 'low', auditLog: false, requireApproval: false }
  },
  'tech-lead': {
    autonomyLevel: 'N1',
    features: { autoScan: true, fileWatching: true, notifications: true, reviewRequired: true, teamMetrics: true },
    security: { level: 'medium', auditLog: true, requireApproval: true }
  },
  'automator': {
    autonomyLevel: 'N3',
    features: { autoScan: true, fileWatching: true, notifications: true, ciIntegration: true, pipelineHooks: true },
    security: { level: 'medium', auditLog: true, requireApproval: false }
  },
  'enterprise': {
    autonomyLevel: 'N1',
    features: { autoScan: true, fileWatching: true, notifications: true, reviewRequired: true, ssoEnabled: true, complianceMode: true },
    security: { level: 'high', auditLog: true, requireApproval: true, encryptionAtRest: true, auditRetentionDays: 365 }
  },
  'custom': {
    autonomyLevel: 'N2',
    features: { autoScan: false, fileWatching: false, notifications: false },
    security: { level: 'medium', auditLog: false, requireApproval: false }
  }
}

export class ConfigGenerator {
  generate(answers: Map<string, Record<string, string | number | boolean | string[]>>, profile: ProfileType): string {
    const preset = PROFILE_PRESETS[profile] ?? PROFILE_PRESETS['solo-dev']
    const lines: string[] = []

    lines.push('# IDEIA Configuration')
    lines.push('# Generated by Onboarding Wizard')
    lines.push('')
    lines.push('version: "1.0"')
    lines.push('')
    lines.push('project:')

    const project = this.buildProjectSection(answers)
    for (const [k, v] of Object.entries(project)) {
      const val = typeof v === 'string' ? v : JSON.stringify(v)
      lines.push(`  ${k}: ${val}`)
    }

    lines.push('')
    lines.push(`profile: ${profile}`)
    lines.push('')
    lines.push('autonomy:')
    lines.push(`  level: ${preset.autonomyLevel}`)
    lines.push('')
    lines.push('features:')
    for (const [k, v] of Object.entries(preset.features)) {
      lines.push(`  ${k}: ${v}`)
    }

    lines.push('')
    lines.push('security:')
    for (const [k, v] of Object.entries(preset.security)) {
      const val = typeof v === 'string' ? v : JSON.stringify(v)
      lines.push(`  ${k}: ${val}`)
    }

    return lines.join('\n') + '\n'
  }

  getPreset(profile: ProfileType): ConfigPreset {
    return { ...(PROFILE_PRESETS[profile] ?? PROFILE_PRESETS['solo-dev']) }
  }

  generateFromSummary(summary: WizardSummary): string {
    const preset = PROFILE_PRESETS[summary.profile] ?? PROFILE_PRESETS['solo-dev']
    const lines: string[] = []

    lines.push('# IDEIA Configuration')
    lines.push('# Generated by Onboarding Wizard')
    lines.push(`# Profile: ${summary.profileLabel}`)
    lines.push(`# Autonomy: ${summary.autonomyLevel}`)
    lines.push('')
    lines.push('version: "1.0"')
    lines.push('')
    lines.push('project:')
    for (const [key, value] of Object.entries(summary.config)) {
      const val = typeof value === 'string' ? value : JSON.stringify(value)
      lines.push(`  ${key}: ${val}`)
    }
    lines.push('')
    lines.push(`profile: ${summary.profile}`)
    lines.push('')
    lines.push('autonomy:')
    lines.push(`  level: ${summary.autonomyLevel}`)
    lines.push('')
    lines.push('features:')
    for (const [k, v] of Object.entries(preset.features)) {
      lines.push(`  ${k}: ${v}`)
    }
    lines.push('')
    lines.push('security:')
    for (const [k, v] of Object.entries(preset.security)) {
      const val = typeof v === 'string' ? v : JSON.stringify(v)
      lines.push(`  ${k}: ${val}`)
    }
    return lines.join('\n') + '\n'
  }

  private buildProjectSection(answers: Map<string, Record<string, string | number | boolean | string[]>>): Record<string, unknown> {
    const section: Record<string, unknown> = {}
    for (const [, stepAnswers] of answers) {
      for (const [key, value] of Object.entries(stepAnswers)) {
        if (key !== 'profile' && key !== 'confirm') {
          section[key] = value
        }
      }
    }
    return section
  }
}
