import type { KnowledgeEntry } from '../knowledge-entries';

export const ENTRIES: KnowledgeEntry[] = [
{
    id: 'llm-architecture',
    title: 'LLM Application Architecture Patterns',
    category: 'ai',
    tags: ['llm', 'ai', 'architecture', 'prompt', 'rag', 'agent'],
    summary: 'Padroes arquiteturais para construir aplicacoes com Large Language Models (LLMs).',
    content: 'Padroes: Simple Prompt (entrada ÔåÆ LLM ÔåÆ saida), RAG (Retrieval-Augmented Generation ÔÇö busca contexto antes do prompt), Agent (LLM decide acoes, usa ferramentas, itera), Chain (sequencia de prompts encadeados), Router (LLM decide qual caminho seguir), Multi-Agent (agentes especializados colaboram). Em producao: caching de respostas, rate limiting, fallback para modelos menores, observabilidade (tokens, latencia, custo).',
    when_to_use: ['Assistentes de IA', 'Automacao inteligente', 'Processamento de linguagem natural'],
  },
{
    id: 'rag-pattern',
    title: 'RAG ÔÇö Retrieval-Augmented Generation',
    category: 'ai',
    tags: ['rag', 'retrieval', 'vector-db', 'embeddings', 'llm'],
    summary: 'RAG combina recuperacao de informacao (vector search) com geracao de texto (LLM) para respostas precisas e contextualizadas.',
    content: 'Pipeline: 1) Ingestion: documentos ÔåÆ chunks ÔåÆ embeddings ÔåÆ vector store. 2) Retrieval: query ÔåÆ embedding ÔåÆ similar search ÔåÆ top-k chunks. 3) Generation: prompt + retrieved chunks ÔåÆ LLM ÔåÆ resposta. Variantes: Naive RAG (simples), Advanced RAG (pre/post-processing, re-ranking, query transform), Modular RAG (componentes intercambiaveis). Ferramentas: LangChain, LlamaIndex, ChromaDB, Pinecone, Weaviate.',
    when_to_use: ['Chatbots com base de conhecimento', 'Perguntas sobre documentos', 'Suporte ao cliente'],
    references: ['Lewis et al. - Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks'],
  },
{
    id: 'vector-database',
    title: 'Vector Databases (ChromaDB, Pinecone, Qdrant, Weaviate)',
    category: 'ai',
    tags: ['vector-db', 'embeddings', 'similarity', 'rag', 'semantic-search'],
    summary: 'Vector databases armazenam e consultam embeddings por similaridade semantica, essenciais para RAG e semantic search.',
    content: 'Indexing: HNSW (Hierarchical Navigable Small World ÔÇö mais rapido), IVF (Inverted File Index ÔÇö menos memoria). Distance: cosine, euclidean, dot product. Ferramentas open-source: ChromaDB (embarcado, simples), Qdrant (Rust, performatico), Weaviate (Go, schema rico), Milvus (escalavel). Cloud: Pinecone, Weaviate Cloud. H├¡brido: PostgreSQL + pgvector (se ja usa Postgres).',
    when_to_use: ['Semantic search', 'RAG pipeline', 'Recomendacao por similaridade'],
  },
{
    id: 'prompt-engineering',
    title: 'Prompt Engineering Patterns',
    category: 'ai',
    tags: ['prompt', 'engineering', 'llm', 'few-shot', 'cot', 'instruction'],
    summary: 'Tecnicas para projetar prompts eficazes para LLMs, incluindo few-shot, chain-of-thought e role prompting.',
    content: 'Tecnicas: Zero-shot (instrucao direta), Few-shot (exemplos no prompt), Chain-of-Thought (raciocinio passo a passo), Tree-of-Thought (multiplas linhas de raciocinio), Role Prompting ("Voce e um engenheiro Senior..."), System Prompt (instrucao de sistema), Output Formatting (JSON, XML), Iterative Refinement (refinar resposta). Dicas: especifico > generico, exemplo > descricao, negativo ("nao faca X") vs positivo ("faca Y").',
    when_to_use: ['Toda interacao com LLM'],
    references: ['OpenAI Prompt Engineering Guide', 'Anthropic Prompt Engineering'],
  },
{
    id: 'ai-agents',
    title: 'AI Agent Architecture ÔÇö Planning, Tools, Memory',
    category: 'ai',
    tags: ['agents', 'ai', 'planning', 'tools', 'memory', 'autonomous'],
    summary: 'AI Agents sao sistemas autonomos que planejam, usam ferramentas e mantem memoria para resolver tarefas complexas.',
    content: 'Componentes: Planner (define passos), Executor (executa acoes com tools), Memory (curto prazo = conversa, longo prazo = vector store), Reflection (avalia resultados e itera). Tool Use: LLM decide qual ferramenta chamar (search, code, API), executa e processa resultado. Multi-Agent: agentes especializados (planner, coder, reviewer) colaboram. Frameworks: LangChain Agents, CrewAI, AutoGen, OpenAI Assistants.',
    when_to_use: ['Automacao de tarefas complexas', 'Codigo autonomo', 'Pesquisa e analise'],
  },
{
    id: 'embeddings',
    title: 'Embeddings & Semantic Representation',
    category: 'ai',
    tags: ['embeddings', 'vectors', 'semantic', 'openai', 'text-embedding'],
    summary: 'Embeddings convertem texto em vetores numericos que capturam significado semantico para similaridade e search.',
    content: 'Modelos: OpenAI text-embedding-3-small/large, Cohere embed, sentence-transformers (open-source), Ollama nomic-embed-text (local). Dimensoes: 384 (small) a 3072 (large). Quanto menor a distancia cosine entre embeddings, mais similares semanticamente. Praticas: normalizar embeddings, batch processing, caching embeddings para evitar recomputar. Para codigo: code-specific embeddings (StarCoder, CodeBERT).',
    when_to_use: ['Semantic search', 'RAG', 'Classificacao de texto', 'Recomendacao'],
  },
{
    id: 'fine-tuning-vs-rag',
    title: 'Fine-Tuning vs RAG ÔÇö When to Use What',
    category: 'ai',
    tags: ['fine-tuning', 'rag', 'llm', 'training', 'retrieval'],
    summary: 'Comparacao entre Fine-Tuning (treinar modelo com dados proprios) e RAG (buscar contexto externo) para LLMs.',
    content: 'Fine-Tuning: altera pesos do modelo com dados especificos. Melhor para: estilo/tom consistente, aprender formato especifico (SQL, JSON), conhecimento profundo de dominio fechado. RAG: nao altera modelo, busca contexto externo. Melhor para: conhecimento atualizado, documentos grandes, dados que mudam frequentemente, evitar alucinacoes. Ambos sao complementares: Fine-Tuning para comportamento, RAG para conhecimento.',
    when_to_use: ['Fine-Tuning: tom/estilo, formato saida', 'RAG: conhecimento, documentos, dados recentes'],
    references: ['OpenAI - Fine-tuning vs RAG', 'LangChain Blog'],
  },
{
    id: 'multi-modal-ai',
    title: 'Multi-Modal AI (Text, Image, Audio, Video)',
    category: 'ai',
    tags: ['multi-modal', 'vision', 'gpt-4v', 'clip', 'diffusion'],
    summary: 'Modelos multi-modais processam e geram multiplos tipos de dados: texto, imagens, audio e video.',
    content: 'Modelos: GPT-4V/4o (texto + imagem), Claude 3.5 Vision (texto + imagem), DALL-E 3/Flux (texto ÔåÆ imagem), Whisper (audio ÔåÆ texto), ElevenLabs (texto ÔåÆ audio), Stable Diffusion (texto ÔåÆ imagem). Use cases: analise de imagens e documentos, geracao de imagens, transcricao de audio, video understanding. Arquitetura: modelos encoders especificos + projection layer para espaco compartilhado.',
    when_to_use: ['Analise de documentos com imagens', 'Geracao de conteudo', 'Transcricao'],
  },
];
