import type { KnowledgeEntry } from '../knowledge-entries';
import { createLogger } from '@ideia/logger';

export const ENTRIES: KnowledgeEntry[] = [
{
    id: 'clean-architecture',
    title: 'Clean Architecture (Robert C. Martin)',
    category: 'architecture',
    tags: ['clean-architecture', 'layers', 'dependency-inversion', 'solid'],
    summary: 'Clean Architecture organiza o codigo em camadas conc├¬ntricas onde dependencias apontam para dentro.',
    content: 'Camadas: Entities ÔåÆ Use Cases ÔåÆ Interface Adapters ÔåÆ Frameworks & Drivers. A Regra de Dependencia: dependencias de codigo-fonte so podem apontar para dentro. Nada em um circulo interno pode saber sobre algo em um circulo externo.',
    principles: ['Dependency Inversion: modulos de alto nivel nao dependem de modulos de baixo nivel', 'Entities: regras de negocio corporativas', 'Use Cases: regras de negocio da aplicacao', 'Interface Adapters: convertem formatos', 'Frameworks: detalhes (banco, web, UI)'],
    when_to_use: ['Projetos de longo prazo', 'Sistemas com regras de negocio complexas', 'Equipes grandes trabalhando em paralelo'],
    when_not_to_use: ['Prototipos rapidos', 'Scripts descartaveis', 'Projetos muito pequenos (< 3 meses)'],
  },
{
    id: 'domain-driven-design',
    title: 'Domain-Driven Design (Eric Evans)',
    category: 'architecture',
    tags: ['ddd', 'domain', 'ubiquitous-language', 'bounded-context', 'aggregate'],
    summary: 'DDD foca em modelar o dominio do negocio com uma linguagem ubiqua compartilhada entre devs e especialistas.',
    content: 'Building Blocks: Entity (identidade), Value Object (atributos), Aggregate (transacoes), Repository (persistencia), Domain Event (efeitos colaterais), Service (operacoes sem estado), Factory (criacao).',
    principles: ['Linguagem Ubiqua: mesmo vocabulario em codigo e conversas', 'Bounded Context: limites explicitos entre subdominios', 'Aggregates: consistencia transacional dentro de boundaries'],
    when_to_use: ['Dominio complexo e em evolucao', 'Equipes precisam de comunicacao clara', 'Sistemas com regras de negocio ricas'],
    when_not_to_use: ['CRUD simples', 'Sistemas onde o dominio e trivial'],
    references: ['Eric Evans - Domain-Driven Design (2003)', 'Vernon - Implementing Domain-Driven Design'],
  },
{
    id: 'cqrs',
    title: 'CQRS ÔÇö Command Query Responsibility Segregation',
    category: 'architecture',
    tags: ['cqrs', 'commands', 'queries', 'event-sourcing', 'read-model'],
    summary: 'CQRS separa operacoes de leitura (Queries) e escrita (Commands) em modelos diferentes.',
    content: 'Commands: alteram estado, retornam void, validados pelo dominio. Queries: leem estado, retornam dados, otimizadas para exibicao. Models separados: write model (consistente) e read model (desnormalizado).',
    principles: ['Commands: imperativos, validacao de negocio, eventos', 'Queries: sem efeitos colaterais, sem regras de negocio', 'Read model pode divergir do write model'],
    when_to_use: ['Read/write ratio muito alto', 'Read models complexos que impactam performance de escrita', 'Equipes separadas para leitura e escrita'],
    when_not_to_use: ['CRUD simples', 'Sistema pequeno onde complexidade adicional nao se justifica'],
  },
{
    id: 'event-sourcing',
    title: 'Event Sourcing',
    category: 'architecture',
    tags: ['event-sourcing', 'events', 'immutability', 'audit', 'replay'],
    summary: 'Event Sourcing armazena o estado como uma sequencia imutavel de eventos, em vez de apenas o estado atual.',
    content: 'Cada alteracao no estado gera um evento imutavel. O estado atual e obtido fazendo replay dos eventos. Beneficios: audit trail completo, time travel, debugging, CQRS natural.',
    principles: ['Nunca deletar ou alterar eventos passados', 'Eventos representam fatos no passado', 'Projections constroem read models a partir de eventos'],
    when_to_use: ['Audit trail e obrigatorio', 'Time travel debugging necessario', 'Sistemas financeiros, compliance'],
    when_not_to_use: ['Sistemas simples onde audit trail nao e requisito', 'Volume extremamente alto de escritas'],
    references: ['Martin Fowler - Event Sourcing', 'Greg Young - CQRS/ES'],
  },
{
    id: 'hexagonal-architecture',
    title: 'Hexagonal Architecture (Ports & Adapters)',
    category: 'architecture',
    tags: ['hexagonal', 'ports', 'adapters', 'dependency-injection'],
    summary: 'Arquitetura Hexagonal isola o nucleo do negocio de tecnologias externas usando Ports (interfaces) e Adapters (implementacoes).',
    content: 'Nucleo (Core): contem regras de negocio puras. Ports: interfaces definidas pelo core. Adapters: implementacoes concretas (bancos, APIs, UI). Toda comunicacao externa passa por ports.',
    principles: ['Core nao depende de nada externo', 'Tecnologias sao detalhes substituiveis', 'Testabilidade: core testavel sem infraestrutura'],
    when_to_use: ['Projetos que precisam trocar tecnologias', 'Alta testabilidade e requisito', 'Microservicos'],
    when_not_to_use: ['Scripts simples', 'Projetos com tecnologia fixa e sem expectativa de troca'],
  },
{
    id: 'microservices',
    title: 'Microservices Architecture',
    category: 'architecture',
    tags: ['microservices', 'distributed-systems', 'decentralized', 'bounded-context'],
    summary: 'Microservices sao servicos pequenos, independentes e focados em um unico bounded context.',
    content: 'Cada servico tem seu proprio banco, deploy independente, e se comunica via APIs (REST, gRPC, eventos). Governanca descentralizada, escalabilidade independente, equipes autonomas.',
    principles: ['Servicos pequenos o suficiente para serem mantidos por uma equipe', 'Banco proprio por servico', 'Comunicacao via APIs bem definidas', 'Deploy independente'],
    when_to_use: ['Equipes grandes e autonomas', 'Escalabilidade independente necessaria', 'Diferentes tecnologias para diferentes problemas'],
    when_not_to_use: ['Equipe pequena', 'Sistema simples', 'Sem infraestrutura de deploy madura'],
    references: ['Sam Newman - Building Microservices', 'Martin Fowler - Microservices'],
  },
{
    id: 'event-driven',
    title: 'Event-Driven Architecture',
    category: 'architecture',
    tags: ['event-driven', 'events', 'pub-sub', 'message-broker', 'kafka', 'rabbitmq'],
    summary: 'Arquitetura orientada a eventos onde servicos se comunicam atraves de eventos assincronos.',
    content: 'Produtores emitem eventos sem saber quem consome. Consumidores reagem a eventos de forma independente. Message Broker (Kafka, RabbitMQ) gerencia entrega. Beneficios: baixo acoplamento, escalabilidade, resiliencia. Desafios: consistencia eventual, debug complexo, idempotencia.',
    principles: ['Eventos representam fatos', 'Produtores nao sabem quem consome', 'Consumidores sao independentes'],
    when_to_use: ['Comunicacao assincrona entre servicos', 'Workflows longos', 'Integracao com sistemas legados'],
    references: ['Martin Fowler - Event-Driven Architecture'],
  },
{
    id: 'ddd-aggregate',
    title: 'DDD Aggregate Design',
    category: 'architecture',
    tags: ['ddd', 'aggregate', 'consistency', 'transaction', 'boundary'],
    summary: 'Aggregate e um cluster de objects tratados como uma unidade para mudancas de estado, com consistencia transacional.',
    content: 'Regras: 1) Escolha um Aggregate Root (entidade que orquestra). 2) Referencie outros aggregates apenas por ID, nao por objeto. 3) Use Eventual Consistency entre aggregates. 4) Uma transacao = um aggregate. 5) Aggregates pequenos para escalabilidade. 6) Limite: o aggregate deve ser pequeno o suficiente para ser carregado em memoria.',
    principles: ['Consistencia forte dentro do aggregate', 'Consistencia eventual entre aggregates', 'Aggregate Root e a unica porta de entrada'],
    when_to_use: ['Sistemas DDD', 'Microservicos com consistencia eventual'],
    references: ['Vaughn Vernon - Implementing Domain-Driven Design', 'Eric Evans - DDD Reference'],
  },
{
    id: 'saga-pattern',
    title: 'Saga Pattern (Distributed Transactions)',
    category: 'architecture',
    tags: ['saga', 'distributed-transactions', 'microservices', 'compensation', 'orchestration'],
    summary: 'Saga gerencia transacoes distribuidas em microservicos usando uma sequencia de transacoes locais com compensacao.',
    content: 'Tipos: Choreography (cada servico publica evento e reage a eventos), Orchestration (orquestrador central coordena passos). Cada passo tem uma transacao compensatoria em caso de falha. Nao ha lock global, consistencia eventual.',
    when_to_use: ['Transacoes que cruzam multiplos servicos', 'Microsservicos', 'Workflows longos'],
    references: ['Caitie McCaffrey - Sagas'],
  },
{
    id: 'api-gateway',
    title: 'API Gateway Pattern',
    category: 'architecture',
    tags: ['api-gateway', 'microservices', 'routing', 'authentication', 'rate-limiting'],
    summary: 'API Gateway e um ponto unico de entrada para microservicos, gerenciando roteamento, auth e limitacao.',
    content: 'Funcoes: roteamento para servicos internos, autenticacao/authorization, rate limiting, caching, logging, transformacao de protocolos. Tipos: Gateway simples (roteamento), BFF (Backend for Frontend ÔÇö gateway por tipo de cliente).',
    when_to_use: ['Multiplos microservicos', 'Diferentes tipos de clientes (web, mobile, IoT)'],
    references: ['Sam Newman - Building Microservices'],
  },
{
    id: 'strangler-fig',
    title: 'Strangler Fig Pattern (Legacy Migration)',
    category: 'architecture',
    tags: ['strangler-fig', 'legacy', 'migration', 'refactoring'],
    summary: 'Strangler Fig permite migrar sistemas legados gradualmente, substituindo funcionalidades uma a uma.',
    content: 'Crie um novo sistema ao lado do legado. Roteie funcionalidades gradualmente para o novo. Remova funcionalidades do legado a medida que sao migradas. Eventualmente o legado inteiro e substituido. Risco baixo: cada peca pode ser testada isoladamente e rollback e simples.',
    when_to_use: ['Migracao de sistemas legados', 'Refactoring de grandes sistemas'],
    references: ['Martin Fowler - StranglerFigApplication'],
  },
{
    id: 'async-communication',
    title: 'Async Communication ÔÇö Message Queue, Pub/Sub, Event Bus',
    category: 'architecture',
    tags: ['async', 'message-queue', 'pub-sub', 'event-bus', 'kafka', 'rabbitmq'],
    summary: 'Comunicacao assincrona entre servicos usando filas de mensagem, publish/subscribe ou event bus.',
    content: 'Message Queue: produtor envia, consumidor recebe (ponto a ponto). Pub/Sub: produtor publica, varios consumidores recebem. Event Bus: barramento central que roteia eventos. Garantias: at-most-once (perda possivel), at-least-once (duplicata possivel), exactly-once (ideal, dificil). Mensagens mortas: DLQ (Dead Letter Queue).',
    when_to_use: ['Desacoplar servicos', 'Processamento em background', 'Workflows longos'],
    references: ['Enterprise Integration Patterns (Hohpe, Woolf)'],
  },
{
    id: 'anti-corruption-layer',
    title: 'Anti-Corruption Layer (ACL)',
    category: 'architecture',
    tags: ['acl', 'anti-corruption', 'legacy', 'boundary', 'translation'],
    summary: 'ACL isola o dominio moderno do legado, traduzindo conceitos e evitando contaminacao do codigo novo.',
    content: 'ACL fica entre o novo sistema e o legado. Funcoes: traduz modelos de dados, adapta protocolos, esconde complexidade, protege o dominio. Implementacao: Gateway (traduz chamadas), Adapter (adapta interface), Facade (simplifica). Exemplo: novo sistema de pedidos se comunica com ERP legado via ACL que traduz XML arcaico para objetos modernos.',
    when_to_use: ['Migracao de legado', 'Integracao com sistemas externos antigos', 'Proteger bounded context'],
    references: ['Eric Evans - DDD', 'Martin Fowler - AntiCorruptionLayer'],
  },
{
    id: 'service-mesh',
    title: 'Service Mesh (Istio, Linkerd)',
    category: 'architecture',
    tags: ['service-mesh', 'istio', 'linkerd', 'sidecar', 'mTLS'],
    summary: 'Service Mesh gerencia comunicacao entre microservicos com sidecar proxies, adicionando observabilidade, seguranca e controle de trafego.',
    content: 'Sidecar: proxy (Envoy) junto a cada servico. Control Plane: gerencia configuracao dos proxies (Istiod). Funcionalidades: mTLS automatico, circuit breaking, canary/traffic splitting, tracing distribuido, metricas. Istio: mais recursos, mais complexo. Linkerd: mais leve, focado em simplicidade. Quando usar: muitos servicos (>20), necessidade de mTLS, observabilidade avancada.',
    when_to_use: ['Microservicos em producao', 'mTLS obrigatorio', 'Multiplas linguagens'],
  },
{
    id: 'sidecar',
    title: 'Sidecar Pattern',
    category: 'architecture',
    tags: ['sidecar', 'microservices', 'proxy', 'container', 'deployment'],
    summary: 'Sidecar e um container auxiliar que acompanha o container principal, adicionando funcionalidades sem modifica-lo.',
    content: 'Sidecar compartilha o mesmo pod/maquina que o container principal. Exemplos: Envoy proxy (service mesh), log aggregator (Filebeat), config reloader, metrics exporter. Beneficios: separacao de concerns, reutilizacao (mesmo sidecar para diferentes aplicacoes), independente de linguagem. Custo: recurso extra, complexidade de deploy.',
    when_to_use: ['Adicionar logging/monitoring transversal', 'Service mesh', 'Config reload'],
  },
{
    id: 'backends-for-frontends',
    title: 'Backends for Frontends (BFF)',
    category: 'architecture',
    tags: ['bff', 'backend', 'frontend', 'gateway', 'mobile', 'web'],
    summary: 'BFF cria um backend especifico para cada tipo de cliente (web, mobile, IoT), otimizando a API para cada um.',
    content: 'Problema: backend unico tenta servir todos os clientes com o mesmo contrato, resultando em over/under fetching. Solucao: cada cliente tem seu proprio BFF que agrega dados e adapta respostas. Exemplo: Web BFF retorna HTML + dados, Mobile BFF retorna JSON otimizado com payloads menores, IoT BFF retorna binario compacto. Beneficios: performance, autonomia de times, evolucao independente.',
    when_to_use: ['Multiplos tipos de cliente', 'Mobile com requisitos diferentes de web', 'Equipes autonomas'],
    references: ['Sam Newman - Backends for Frontends'],
  },
{
    id: 'ambassador',
    title: 'Ambassador / Proxy Pattern',
    category: 'architecture',
    tags: ['ambassador', 'proxy', 'sidecar', 'external', 'broker'],
    summary: 'Ambassador atua como intermediario entre a aplicacao e servicos externos, centralizando concerns de comunicacao.',
    content: 'Diferenca de Sidecar: ambassador foca em comunicacao externa, sidecar em funcionalidades auxiliares. Funcionalidades: circuit breaking, retry, timeout, caching, autenticacao, rate limiting. Exemplo: Redis Sentinel como ambassador para cluster Redis. Implementacao: Envoy, HAProxy, Nginx como ambassadors.',
    when_to_use: ['Comunicacao com servicos externos', 'Centralizar config de resiliencia'],
  },
{
    id: 'event-sourcing-cqrs',
    title: 'CQRS + Event Sourcing Combined',
    category: 'architecture',
    tags: ['cqrs', 'event-sourcing', 'combined', 'projection', 'read-model'],
    summary: 'CQRS + Event Sourcing combinados: command side armazena eventos imutaveis, query side projeta read models otimizados.',
    content: 'Fluxo: 1) Command ÔåÆ valida regras ÔåÆ gera evento(s). 2) Event store persiste evento. 3) Event bus publica evento. 4) Projections consomem evento e atualizam read models. 5) Query responde a partir de read models. Beneficios: audit trail completo, read models otimizados, time travel. Desafios: consistencia eventual, complexidade de projecoes, schema evolution de eventos.',
    when_to_use: ['Audit trail obrigatorio', 'Read models muito diferentes do write model', 'Sistemas complexos'],
  },
{
    id: 'serverless',
    title: 'Serverless Architecture (Lambda, Functions)',
    category: 'architecture',
    tags: ['serverless', 'lambda', 'faas', 'aws', 'azure', 'cloud'],
    summary: 'Serverless executa codigo sem gerenciar servidores, escalando automaticamente e cobrando por execucao.',
    content: 'FaaS: Functions as a Service (AWS Lambda, Azure Functions, Cloud Functions). Event Sources: HTTP (API Gateway), fila (SQS), stream (Kinesis), timer (EventBridge). Beneficios: zero administracao, escalabilidade automatica, pagamento por uso. Limitacoes: cold start, timeout (15 min Lambda), stateless, complexidade de debug local. Frameworks: Serverless Framework, AWS SAM, SST.',
    when_to_use: ['Event-driven tasks', 'APIs de baixo trafego com picos', 'Processamento batch', 'Prototipos'],
  },
{
    id: 'pipeline-architecture',
    title: 'Pipeline Architecture',
    category: 'architecture',
    tags: ['pipeline', 'batch', 'etl', 'stream', 'processing'],
    summary: 'Pipeline architecture processa dados em estagios encadeados, onde cada estagio transforma e passa adiante.',
    content: 'Estagios: Source ÔåÆ Filter ÔåÆ Transform ÔåÆ Enrich ÔåÆ Store ÔåÆ Notify. Cada estagio pode ser paralelizado ou escalado independentemente. Tipos: Batch (processa lotes em intervalos, ex: ETL diario), Stream (processa em tempo real, ex: Kafka Streams, Flink). Fila entre estagios: desacopla e permite backpressure. Exemplos: pipeline de dados, pipeline CI/CD, pipeline de processamento de imagens.',
    when_to_use: ['Processamento de dados em etapas', 'ETL', 'Streaming', 'CI/CD'],
  },
{
    id: 'layered-architecture',
    title: 'Layered Architecture (N-Tier)',
    category: 'architecture',
    tags: ['layered', 'n-tier', 'presentation', 'business', 'data'],
    summary: 'Layered architecture organiza o codigo em camadas horizontais (apresentacao, negocio, dados) onde cada camada so depende da imediatamente inferior.',
    content: 'Camadas tipicas: Presentation (controllers, views), Application (use cases, DTOs), Domain (entities, rules), Infrastructure (database, external APIs). Regras: dependencia apenas para baixo, cada camada tem responsabilidade distinta. Vantagens: simplicidade, separacao de concerns. Desvantagens: tendencia a vazamento de camadas (skip layers), terminologia varia entre projetos.',
    when_to_use: ['Projetos simples a medios', 'Equipes pequenas', 'Sistemas CRUD'],
  },
{
    id: 'onion-architecture',
    title: 'Onion Architecture',
    category: 'architecture',
    tags: ['onion', 'hexagonal', 'clean', 'dependency-inversion'],
    summary: 'Onion Architecture coloca o dominio no centro, com camadas conc├¬ntricas dependendo para dentro, similar a Clean Architecture.',
    content: 'Camadas de dentro para fora: Domain Model (entities, value objects), Domain Services (regras de negocio), Application Services (use cases), Infrastructure (banco, API, UI). Dependencia: circulos externos dependem dos internos, nunca o contrario. Interface Adapters: camada que converte dados entre formatos. Similar a Hexagonal e Clean, com enfase em dominios ricos.',
    when_to_use: ['DDD', 'Sistemas complexos', 'Projetos de longo prazo'],
  },
];
