import type { KnowledgeEntry } from '../knowledge-entries';

export const ENTRIES: KnowledgeEntry[] = [
{
    id: '12-factor-app',
    title: '12-Factor App',
    category: 'devops',
    tags: ['12-factor', 'cloud-native', 'heroku', 'saas', 'config', 'logs'],
    summary: '12-Factor App e uma metodologia para construir aplicacoes SaaS modernas e cloud-native.',
    content: '1. Codebase: um repositorio, muitos deploys. 2. Dependencies: declaradas e isoladas. 3. Config: armazenada em variaveis de ambiente. 4. Backing Services: tratados como recursos anexaveis. 5. Build, Release, Run: separacao estrita. 6. Processes: stateless. 7. Port Binding: exporta servicos via porta. 8. Concurrency: escala via modelo de processos. 9. Disposability: inicializacao e desligamento rapidos. 10. Dev/Prod Parity: similaridade maxima. 11. Logs: streams de eventos. 12. Admin Processes: tarefas administrativas como one-off.',
    when_to_use: ['Aplicacoes cloud-native', 'SaaS', 'Qualquer aplicacao web moderna'],
    references: ['https://12factor.net/'],
  },
{
    id: 'observability-patterns',
    title: 'Observability ÔÇö Logging, Metrics, Tracing',
    category: 'devops',
    tags: ['observability', 'logging', 'metrics', 'tracing', 'opentelemetry', 'monitoring'],
    summary: 'Os tres pilares da observabilidade: logging estruturado, metricas e tracing distribuido.',
    content: 'Logging: estruturado (JSON), com correlation ID, niveis (debug, info, warn, error). Metrics: counters, gauges, histograms, rate (RED method: Rate, Errors, Duration). Tracing: spans com contexto, distributed traces (OpenTelemetry). Dashboards: mostram saude do sistema. Alerts: baseados em SLOs. (USE method: Utilization, Saturation, Errors para infraestrutura).',
    when_to_use: ['Sistemas em producao', 'Microservicos', 'Qualquer sistema onde downtime custa dinheiro'],
    references: ['OpenTelemetry Specification', 'Google SRE Books'],
  },
{
    id: 'feature-toggles',
    title: 'Feature Toggles (Feature Flags)',
    category: 'devops',
    tags: ['feature-toggles', 'flags', 'continuous-delivery', 'canary', 'a-b-testing'],
    summary: 'Feature Toggles permitem ligar/desligar funcionalidades sem fazer deploy, habilitando entrega continua e canary releases.',
    content: 'Tipos: Release Toggles (incompleto em producao), Experiment Toggles (A/B testing), Ops Toggles (controle operacional), Permission Toggles (acesso gradual). Boas praticas: toggles temporarios (remover apos uso), codigo morto por toggle = divida tecnica. Ferramentas: LaunchDarkly, Flagsmith, Unleash.',
    when_to_use: ['Continuous Delivery', 'Canary releases', 'A/B testing', 'Early access para beta users'],
    references: ['Martin Fowler - Feature Toggles', 'Pete Hodgson - Feature Toggles'],
  },
{
    id: 'health-check',
    title: 'Health Check & Readiness Patterns',
    category: 'devops',
    tags: ['health-check', 'readiness', 'liveness', 'kubernetes', 'monitoring'],
    summary: 'Health checks permitem que orquestradores e load balancers saibam se a aplicacao esta saudavel e pronta para trafego.',
    content: 'Liveness: aplicacao esta viva (ping simples). Readiness: aplicacao pronta para receber trafego (dependencias ok). Startup: verificacao inicial (aplicacao acabou de iniciar). Endpoints: /health, /ready, /startup. Em Kubernetes: livenessProbe, readinessProbe, startupProbe.',
    when_to_use: ['Toda aplicacao em producao', 'Kubernetes', 'Load balancers'],
  },
{
    id: 'blue-green-deploy',
    title: 'Blue-Green Deployment',
    category: 'devops',
    tags: ['blue-green', 'deploy', 'zero-downtime', 'rollback'],
    summary: 'Blue-Green mantem dois ambientes identicos (blue e green) e alterna o trafego entre eles para deploy zero-downtime.',
    content: 'Blue: ambiente atual recebendo trafego. Green: novo ambiente com nova versao. Switch: roteador/load balancer muda trafego de blue para green. Rollback: simples ÔÇö volta trafego para blue. Beneficios: zero downtime, rollback instantaneo. Desafio: custo de manter dois ambientes.',
    when_to_use: ['Sistemas criticos que nao podem parar', 'Deploys frequentes'],
  },
{
    id: 'log-strutured',
    title: 'Structured Logging Pattern',
    category: 'devops',
    tags: ['logging', 'structured', 'json', 'observability', 'correlation-id'],
    summary: 'Structured logging emite logs em formato estruturado (JSON) com campos consistentes para facilitar analise.',
    content: 'Campos obrigatorios: timestamp, level, message, service, traceId, spanId. Campos opcionais: userId, requestId, duration, error. JSON como formato padrao. Correlation ID: propaga entre servicos. Niveis: debug (desenvolvimento), info (operacao), warn (potencial problema), error (falha), fatal (crash).',
    when_to_use: ['Toda aplicacao em producao', 'Microservicos', 'Sistemas distribuidos'],
    references: ['Peter Bourgon - Logging v. instrumentation'],
  },
{
    id: 'composition-localstack',
    title: 'Local Stack para Desenvolvimento',
    category: 'devops',
    tags: ['localstack', 'docker', 'dev-env', 'aws', 'testing'],
    summary: 'Use LocalStack para emular servicos AWS localmente durante desenvolvimento e testes.',
    content: 'LocalStack emula S3, DynamoDB, SQS, SNS, Lambda, API Gateway, CloudFormation e mais. Executa em Docker. Beneficios: sem custos AWS, rapido, testavel offline, sem contaminate de ambiente compartilhado.',
    when_to_use: ['Desenvolvimento com servicos AWS', 'Testes offline', 'CI sem acesso a AWS'],
  },
{
    id: 'monorepo-pattern',
    title: 'Monorepo Management Patterns',
    category: 'devops',
    tags: ['monorepo', 'nx', 'turborepo', 'workspaces', 'build', 'dependencies'],
    summary: 'Monorepo mantem multiplos projetos em um unico repositorio com build e dependencias compartilhadas.',
    content: 'Tools: Nx, Turborepo, Lerna, npm/yarn/pnpm workspaces. Beneficios: shared code, refactoring atomicos, CI/CD unificado, dependencias sincronizadas. Desafios: build time, git history grande, gate unificado. Solucoes: build cache (Nx, Turborepo), CI estrategico (mudancas afetam apenas projetos relevantes), CODEOWNERS para permissoes.',
    when_to_use: ['Multiplos pacotes relacionados', 'Equipes que compartilham codigo frequentemente'],
    references: ['Nx Documentation', 'Turborepo Documentation'],
  },
{
    id: 'canary-release',
    title: 'Canary Release Pattern',
    category: 'devops',
    tags: ['canary', 'deploy', 'rollout', 'gradual', 'risk-mitigation'],
    summary: 'Canary release rola uma nova versao para uma pequena porcentagem de usuarios antes de liberar para todos.',
    content: 'Passos: 1) Deploy nova versao ao lado da atual. 2) Roteie X% do trafego para a nova. 3) Monitore metricas (erros, latencia). 4) Se saudavel, aumente gradualmente ate 100%. 5) Se problemas, rollback instantaneo. Ferramentas: Kubernetes (Istio, Flagger), AWS CodeDeploy, LaunchDarkly. Diferenca de Blue-Green: canary e gradual, blue-green e switch instantaneo.',
    when_to_use: ['Mudancas arriscadas', 'Testar em producao com seguranca', 'Validar com usuarios reais'],
    references: ['Martin Fowler - CanaryRelease', 'Google SRE Book'],
  },
{
    id: 'gitops',
    title: 'GitOps ÔÇö Git as Single Source of Truth',
    category: 'devops',
    tags: ['gitops', 'git', 'argocd', 'flux', 'kubernetes', 'iac'],
    summary: 'GitOps usa o repositorio Git como a unica fonte da verdade para infraestrutura e configuracao, com deploy automatico.',
    content: 'Principios: 1) Estado desejado declarado em Git. 2) Operador (ArgoCD, Flux) sincroniza automaticamente. 3) Push vs Pull: operador faz pull do Git para o cluster, sem acesso de CI ao cluster. 4) Toda mudanca e via PR (auditavel, revisivel). Beneficios: rollback com git revert, historico completo, revisao via PR.',
    when_to_use: ['Kubernetes', 'Infraestrutura como Codigo', 'Ambientes regulados (audit trail)'],
    references: ['ArgoCD Documentation', 'Flux Documentation', 'Weaveworks GitOps'],
  },
{
    id: 'iac-patterns',
    title: 'Infrastructure as Code (Terraform, Pulumi, CloudFormation)',
    category: 'devops',
    tags: ['iac', 'terraform', 'pulumi', 'cloudformation', 'infrastructure'],
    summary: 'IaC gerencia infraestrutura (rede, servidores, banco) atraves de codigo versionado, em vez de configuracao manual.',
    content: 'Ferramentas: Terraform/HCL (provider-agnostic, estado em arquivo), Pulumi (TS/JS/Python/Go, estado gerenciado), CloudFormation (AWS-only, YAML/JSON). Praticas: estado remoto (S3 + DynamoDB locking para Terraform), modulos reutilizaveis, plan/review antes de apply, terragrunt para DRY. Dica: evite drift com CI/CD que aplica automaticamente.',
    when_to_use: ['Toda infraestrutura em nuvem', 'Ambientes multiplos (dev/staging/prod)'],
    references: ['Terraform Documentation', 'Pulumi Documentation'],
  },
{
    id: 'docker-best-practices',
    title: 'Docker Best Practices',
    category: 'devops',
    tags: ['docker', 'container', 'multi-stage', 'dockerfile', 'image'],
    summary: 'Boas praticas para criar imagens Docker eficientes, seguras e rapidas.',
    content: 'Multi-stage builds: separe build e runtime para imagens menores (.NET: build SDK + runtime alpine). Ordem de camadas: dependencias estaveis primeiro (package.json ÔåÆ npm ci), codigo depois (maximiza cache). .dockerignore: exclua node_modules, .git, dist. Seguranca: nao rode como root (USER appuser), use imagens oficiais, escaneie com Trivy/Snyk. Imagens pequenas: alpine, distroless.',
    when_to_use: ['Toda aplicacao conteinerizada'],
    references: ['Docker Best Practices Guide'],
  },
{
    id: 'kubernetes-patterns',
    title: 'Kubernetes Patterns (Pod, Service, Ingress, ConfigMap)',
    category: 'devops',
    tags: ['kubernetes', 'k8s', 'pod', 'service', 'ingress', 'configmap'],
    summary: 'Padroes fundamentais do Kubernetes para implantar e gerenciar aplicacoes conteinerizadas.',
    content: 'Pod: menor unidade (1+ containers). Deployment: gerencia replicas e rolling updates. Service: IP estavel e DNS para pods (ClusterIP, NodePort, LoadBalancer). Ingress: entrada HTTP/HTTPS com regras de roteamento. ConfigMap/Secret: configuracao separada do container. PersistentVolume: armazenamento persistente. Probes: liveness, readiness, startup.',
    when_to_use: ['Aplicacoes em producao', 'Microservicos', 'Escalabilidade automatica'],
  },
{
    id: 'helm',
    title: 'Helm Charts ÔÇö Kubernetes Package Manager',
    category: 'devops',
    tags: ['helm', 'kubernetes', 'charts', 'templates', 'package-manager'],
    summary: 'Helm empacota configuracao Kubernetes em Charts reutilizaveis com templates e values parametrizaveis.',
    content: 'Chart: estrutura de diretorio com Chart.yaml, values.yaml, templates/. Template: Go templates que geram YAML Kubernetes. Values: valores default que podem ser sobrescritos (--set, values files). Dependencias: charts podem depender de outros charts. Repositorios: ArtifactHUB, charts.helm.sh. Releases: cada install gera uma release gerenciada.',
    when_to_use: ['Empacotar apps Kubernetes complexas', 'Compartilhar configuracao entre equipes'],
    references: ['Helm Documentation', 'Awesome Helm'],
  },
{
    id: 'immutable-infrastructure',
    title: 'Immutable Infrastructure Pattern',
    category: 'devops',
    tags: ['immutable', 'infrastructure', 'golden-image', 'ami', 'container'],
    summary: 'Immutable Infrastructure substitui servidores em vez de modifica-los apos deploy, garantindo consistencia.',
    content: 'Principio: uma vez criado, um servidor nunca e modificado. Para atualizar: crie nova imagem com mudancas, substitua o servidor. Beneficios: ambiente consistente (sem drift), deploy deterministico, rollback simples (trocar imagem), debug facil (sabe exatamente o que rodava). Implementacao: golden images (AMI), containers (Docker + K8s), Packer (criar imagens).',
    when_to_use: ['Ambientes de producao', 'Microservicos', 'Deploys frequentes'],
    references: ['Chad Fowler - ImmutableDeployments', 'Martin Fowler - PhoenixServer'],
  },
{
    id: 'ci-pipeline-design',
    title: 'CI/CD Pipeline Design Patterns',
    category: 'devops',
    tags: ['ci-cd', 'pipeline', 'github-actions', 'gitlab-ci', 'automation'],
    summary: 'Padroes para projetar pipelines de CI/CD eficientes, rapidos e confiaveis.',
    content: 'Estrategias: Pipeline as Code (YAML versionado), Fast Feedback (testes rapidos primeiro), Matrix Build (multi-versao/OS), Cache Inteligente (node_modules, Docker layers), Parallel Stages (jobs independentes em paralelo), Gate Progressivo (lint ÔåÆ test ÔåÆ security ÔåÆ build ÔåÆ deploy), Artifact Promotion (mesmo artefato em todos ambientes), Fail Fast (cancelar pipeline em falha).',
    when_to_use: ['Todo projeto profissional'],
  },
{
    id: 'monitoring-alerting',
    title: 'Monitoring & Alerting (Prometheus, Grafana)',
    category: 'devops',
    tags: ['monitoring', 'prometheus', 'grafana', 'alerting', 'observability'],
    summary: 'Monitoramento proativo com metricas, dashboards e alertas para manter a saude do sistema.',
    content: 'Prometheus: coleta metricas via pull (scrape), query (PromQL), storage time-series. Grafana: dashboards com visualizacoes. Alertas: definir regras (ex: error_rate > 5% por 5 minutos) ÔåÆ notificacao (Slack, PagerDuty, email). RED method: Rate, Errors, Duration (para servicos). USE method: Utilization, Saturation, Errors (para recursos). SLOs/SLIs: targets de confiabilidade.',
    when_to_use: ['Sistemas em producao', 'SLOs com clientes'],
    references: ['Google SRE Book', 'Prometheus Documentation'],
  },
{
    id: 'semantic-versioning',
    title: 'Semantic Versioning (SemVer)',
    category: 'devops',
    tags: ['semver', 'versioning', 'release', 'compatibility', 'npm'],
    summary: 'SemVer padroniza numeros de versao no formato MAJOR.MINOR.PATCH para comunicar compatibilidade de mudancas.',
    content: 'Formato: MAJOR (incompativel ÔÇö breaking change), MINOR (nova funcionalidade compativel), PATCH (bug fix compativel). Pre-release: 1.0.0-alpha.1, 1.0.0-beta.2. Build metadata: 1.0.0+build.123. Regras: 0.x e para desenvolvimento inicial (qualquer coisa pode mudar). Depois de 1.0.0, MAJOR = breaking, MINOR = feature, PATCH = bugfix. No Node.js: ^1.2.3 (compativel com 1.x.x), ~1.2.3 (compativel com 1.2.x).',
    when_to_use: ['Toda biblioteca/pacote', 'APIs publicas'],
    references: ['semver.org', 'npm semver calculator'],
  },
];
