import type { KnowledgeEntry } from '../knowledge-entries';
import { createLogger } from '@ideia/logger';

export const ENTRIES: KnowledgeEntry[] = [
{
    id: 'cache-strategies',
    title: 'Cache Strategies ÔÇö CDN, Redis, In-Memory',
    category: 'performance',
    tags: ['cache', 'redis', 'cdn', 'performance', 'caching', 'ttl'],
    summary: 'Estrategias de cache para melhorar performance: CDN para conteudo estatico, Redis para dados frequentes, in-memory para dados de calculo.',
    content: 'Estrategias: Cache Aside (aplicacao carrega no cache), Read Through (cache carrega do banco), Write Through (cache escreve no banco), Write Behind (cache acumula e escreve em batch). TTL: tempo de vida do cache. Invalida├º├úo: manual, TTL, evento. CDN: CloudFront, Cloudflare para assets estaticos. Redis: estrutura de dados em memoria com persistencia opcional.',
    when_to_use: ['Dados lidos frequentemente e raramente alterados', 'APIs com alta latencia de origem'],
    references: ['Martin Fowler - CacheAside'],
  },
{
    id: 'lazy-loading',
    title: 'Lazy Loading Pattern',
    category: 'performance',
    tags: ['lazy-loading', 'performance', 'initialization', 'deferred'],
    summary: 'Lazy loading adia a inicializacao de um objeto ate que ele seja realmente necessario, economizando recursos.',
    content: 'Aplicacoes: imagens (loading="lazy"), modulos JS (dynamic import()), rotas (React.lazy), dados (infinite scroll), objetos pesados (Lazy Initialization). Em JS/TS: const Component = React.lazy(() => import("./HeavyComponent")). Beneficios: reduz tempo de carregamento inicial, economia de memoria, melhora percepcao de performance.',
    when_to_use: ['Componentes fora da tela inicial', 'Dados sob demanda', 'Objetos pesados raramente usados'],
  },
{
    id: 'connection-pooling',
    title: 'Connection Pooling',
    category: 'performance',
    tags: ['connection-pool', 'database', 'pool', 'performance', 'tcp'],
    summary: 'Connection pool mantem um conjunto de conexoes abertas e reutilizaveis, evitando custo de abrir/fechar para cada requisicao.',
    content: 'Configuracao: min (conexoes minimas mantidas), max (maximo permitido), idle timeout (fecha conexoes ociosas), max lifetime (recicla conexoes velhas). Beneficios: reduz latencia (evita handshake TCP), limita conexoes simultaneas ao banco, gerencia pressao. Cuidados: pool esgotado = fila de espera, configurar adequadamente ao numero de replicas.',
    when_to_use: ['Bancos de dados', 'APIs externas', 'Redis'],
  },
{
    id: 'http2-http3',
    title: 'HTTP/2 and HTTP/3 Performance',
    category: 'performance',
    tags: ['http2', 'http3', 'performance', 'multiplexing', 'quic'],
    summary: 'HTTP/2 e HTTP/3 trazem melhorias significativas de performance sobre HTTP/1.1.',
    content: 'HTTP/2: multiplexing (multiplas requisicoes em unica conexao TCP), header compression (HPACK), server push, binary protocol. HTTP/3: usa QUIC (UDP em vez de TCP), elimina head-of-line blocking do TCP, conexao 0-RTT, melhor em redes moveis. Adocao: HTTP/2 ja padrao, HTTP/3 suportado por Cloudflare, Google, Facebook. Para APIs: beneficios maiores com multiplos recursos paralelos.',
    when_to_use: ['Aplicacoes web modernas (automatico com CDNs)', 'APIs com multiplos requests paralelos'],
  },
{
    id: 'cdn-strategies',
    title: 'CDN Strategies (CloudFront, Cloudflare, Fastly)',
    category: 'performance',
    tags: ['cdn', 'caching', 'edge', 'cloudfront', 'cloudflare'],
    summary: 'CDN distribui conteudo estatico em servidores geograficamente distribuidos para reduzir latencia.',
    content: 'Cache: assets estaticos (JS, CSS, imagens) com TTL longo e versionamento (hash no filename). Dynamic: API responses podem ser cacheadas com Cache-Control headers e TTL curto. Edge Computing: CloudFront Functions, Cloudflare Workers (codigo na borda). Invalida├º├úo: versionamento > invalidacao por path. Pull vs Push: pull (CDN busca na origem, mais comum), push (envia para CDN).',
    when_to_use: ['Audiencia global', 'Assets estaticos', 'APIs com resposta lenta da origem'],
  },
{
    id: 'code-splitting',
    title: 'Code Splitting & Tree Shaking',
    category: 'performance',
    tags: ['code-splitting', 'tree-shaking', 'bundle', 'webpack', 'vite'],
    summary: 'Code splitting divide o bundle em chunks carregados sob demanda, tree shaking remove codigo morto.',
    content: 'Code Splitting: dynamic import() separa modulos em chunks, carregados apenas quando necessarios. Ex: React.lazy() para rotas. Tree Shaking: bundlers (Webpack, Vite, esbuild) removem exports nao utilizados. Requer ES modules (import/export staticos, nao CommonJS). Side effects: marcar "sideEffects": false em package.json para permitir tree shaking mais agressivo.',
    when_to_use: ['Aplicacoes web grandes', 'Reduzir bundle inicial', 'SPAs com muitas rotas'],
  },
{
    id: 'brotli-compression',
    title: 'Compression (gzip, Brotli, Zstandard)',
    category: 'performance',
    tags: ['compression', 'gzip', 'brotli', 'zstd', 'performance'],
    summary: 'Compressao reduz o tamanho das respostas HTTP, melhorando velocidade de carregamento, especialmente em redes lentas.',
    content: 'gzip: padrao universal, suportado por todos. Brotli: melhor compressao que gzip (20-30% menor), suportado por todos browsers modernos. Zstandard (zstd): alta velocidade de compressao/decompressao. Configuracao: nginx (brotli_static on, gzip_proxied), CDNs ativam automaticamente. Niveis: brotli level 4-6 e bom custo-beneficio entre compressao e CPU.',
    when_to_use: ['Trafego HTTP', 'Assets estaticos', 'APIs com payloads grandes'],
  },
{
    id: 'memory-leak',
    title: 'Memory Leak Detection & Prevention',
    category: 'performance',
    tags: ['memory-leak', 'nodejs', 'v8', 'heap', 'gc', 'debug'],
    summary: 'Memoria e um recurso finito ÔÇö detectar e prevenir leaks e essencial para estabilidade de longa duracao.',
    content: 'Causas comuns em Node.js: closures inesperadas, event listeners nao removidos, globals (global, globalThis), caches sem limite, referencias em timers/setInterval, streams nao fechados, detached DOM. Detect: heap snapshots (Chrome DevTools, --inspect), memory usage monitoring (process.memoryUsage()), leak detection (memlab, clinicjs). Prevencao: WeakRef/WeakMap, clearTimeout/clearInterval, limites de cache, event emitter cleanup.',
    when_to_use: ['Aplicacoes de longa duracao', 'Servidores', 'Processamento batch'],
  },
{
    id: 'async-performance',
    title: 'Async Performance ÔÇö Event Loop, Promise, Worker Threads',
    category: 'performance',
    tags: ['async', 'event-loop', 'worker-threads', 'promise', 'non-blocking'],
    summary: 'Maximizar performance em Node.js usando I/O assincrono, event loop eficiente e CPU-bound em worker threads.',
    content: 'Event Loop: fase unico (timers, I/O callbacks, idle/prepare, poll, check, close). Nao bloquear: tarefas CPU-intensivas bloqueiam event loop. Solucoes: Worker Threads (paralelismo real para CPU), setImmediate() para liberar loop, partitioning (dividir tarefas grandes em chunks com setImmediate). Promises: mais eficientes que callbacks, mas cuidado com Promise.all() que falha rapido (usar Promise.allSettled()).',
    when_to_use: ['Servidores Node.js', 'Processamento intensivo'],
    references: ['Node.js Event Loop Guide', 'Node.js Documentation'],
  },
{
    id: 'responsive-design',
    title: 'Responsive Design Patterns',
    category: 'web',
    tags: ['responsive', 'css', 'mobile', 'media-queries', 'flexbox', 'grid'],
    summary: 'Responsive design adapta a interface para diferentes tamanhos de tela usando CSS Grid, Flexbox e media queries.',
    content: 'Abordagens: Mobile-First (comece pelo menor layout, adicione com min-width), Desktop-First (comece pelo maior, remova com max-width). CSS Grid: layout 2D (linhas + colunas), ideal para paginas inteiras. Flexbox: layout 1D (linha ou coluna), ideal para componentes. Media Queries: breakpoints comuns (480px mobile, 768px tablet, 1024px desktop, 1280px+ wide). Unidades: rem (fontes), % (largura), vw/vh (viewport).',
    when_to_use: ['Toda aplicacao web moderna', 'Sites acessiveis em qualquer dispositivo'],
  },
{
    id: 'pwa',
    title: 'Progressive Web App (PWA) Patterns',
    category: 'web',
    tags: ['pwa', 'service-worker', 'offline', 'manifest', 'cache'],
    summary: 'PWA transforma aplicacoes web em experiencias similares a apps nativos com suporte offline, push e instalacao.',
    content: 'Requisitos: Service Worker (cache, offline, background sync), Web App Manifest (nome, icone, themecolor, display standalone), HTTPS. Cache Strategies: Network First (sempre buscar online, fallback cache), Cache First (servir cache, atualizar em background), Stale-While-Revalidate (cache imediato, atualizacao assincrona). Offline: pagina fallback, IndexedDB para dados. Push: Web Push API (notificacoes mesmo fechado).',
    when_to_use: ['Aplicacoes que precisam funcionar offline', 'Reducao de dependencia de rede', 'Engajamento'],
  },
{
    id: 'offline-first',
    title: 'Offline-First Architecture',
    category: 'web',
    tags: ['offline', 'sync', 'pwa', 'indexeddb', 'local-first'],
    summary: 'Offline-First projeta a aplicacao para funcionar sem conexao, sincronizando dados quando online.',
    content: 'Principios: 1) Operacoes locais primeiro (CRUD em IndexedDB/localStorage). 2) Sincronizacao assincrona quando online. 3) Resolucao de conflitos (last-write-wins, CRDT, operational transform). 4) Feedback de estado (indicar online/offline/pending sync). Bibliotecas: RxDB (PouchDB + sync), Firebase Firestore (offline embutido), localForage, Workbox. Desafios: conflitos de edicao concorrente, consistencia, storage limitado.',
    when_to_use: ['Aplicacoes mobile web', 'Redes instaveis', 'Colaboracao offline'],
  },
{
    id: 'web-performance',
    title: 'Web Performance Metrics (Core Web Vitals)',
    category: 'performance',
    tags: ['web-vitals', 'lcp', 'fid', 'cls', 'performance', 'seo'],
    summary: 'Core Web Vitals sao metricas de performance e experiencia do usuario monitoradas pelo Google para ranking SEO.',
    content: 'LCP (Largest Contentful Paint): <2.5s ÔÇö mede carregamento do maior elemento visivel. FID (First Input Delay): <100ms ÔÇö mede responsividade a interacao do usuario (substituido por INP). INP (Interaction to Next Paint): <200ms. CLS (Cumulative Layout Shift): <0.1 ÔÇö mede estabilidade visual (evitar layout shift sem aviso). TTFB (Time to First Byte): <800ms. Ferramentas: Lighthouse, PageSpeed Insights, Web Vitals Extension, RUM (Real User Monitoring).',
    when_to_use: ['Toda pagina web', 'SEO', 'Experiencia do usuario'],
  },
{
    id: 'resource-hints',
    title: 'Resource Hints (preload, prefetch, preconnect)',
    category: 'web',
    tags: ['preload', 'prefetch', 'preconnect', 'performance', 'resource-hints'],
    summary: 'Resource hints informam o browser sobre recursos futuros para carregamento proativo.',
    content: 'preload: carrega recurso critico com alta prioridade (fontes, hero images, CSS critico). <link rel="preload" href="font.woff2" as="font">. prefetch: carrega recurso para proxima navegacao (baixa prioridade). preconnect: estabelece conexao (DNS + TCP + TLS) com origem terceira antes de precisar. dns-prefetch: apenas DNS (mais leve que preconnect). modulepreload: preload de ES modules. Timing: preload agora, prefetch futuro proximo, preconnect para origens criticas.',
    when_to_use: ['Otimizacao de performance web'],
  },
{
    id: 'ssr-csr',
    title: 'SSR vs CSR vs SSG vs ISR ÔÇö Rendering Strategies',
    category: 'web',
    tags: ['ssr', 'csr', 'ssg', 'isr', 'nextjs', 'nuxt', 'rendering'],
    summary: 'Diferentes estrategias de renderizacao para aplicacoes web com tradeoffs de performance, SEO e dinamismo.',
    content: 'CSR (Client-Side Rendering): React/Vue puro, carrega JS, renderiza no browser. SEO limitado, TTFB rapido, LCP lento. SSR (Server-Side Rendering): Next.js/Nuxt, renderiza no servidor a cada request. SEO otimo, LCP rapido, TTFB mais lento. SSG (Static Site Generation): gera HTML estatico no build. Super rapido, sem dinamismo. ISR (Incremental Static Regeneration): SSG com revalidacao periodica (Next.js). SSG + revalidate a cada X segundos. Streaming SSR: renderiza por partes (React 18).',
    when_to_use: ['CSR: dashboards/admin', 'SSR: conteudo dinamico com SEO', 'SSG: blogs/docs', 'ISR: midway'],
  },
];
